### ISSUE TITLE
Incorrect visualizations on some sample data

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#100]
Ran the following code:

    hvac = sc.textFile('wasb:///HdiSamples/HdiSamples/SensorSampleData/hvac/HVAC.csv')
    from pyspark.sql import Row
    Doc = Row("TargetTemp", "ActualTemp", "System", "SystemAge", "BuildingID")
    def parseDocument(line):
        values = [str(x) for x in line.split(',')]
        return Doc(values[2], values[3], values[4], values[5], values[6])
    documents = hvac.filter(lambda s: "Date" not in s).map(parseDocument)
    df = sqlContext.createDataFrame(documents)
    df.registerTempTable('data')

and then

    %select * from data limit 100

The visualizations, at least for the pie graphs, are wrong.  Screenshot:

![screen shot 2016-01-06 at 6 18 47 pm](https://cloud.githubusercontent.com/assets/13972471/12160578/3bdb966e-b4a2-11e5-97ce-ee297d0ca6cc.png)

Clearly there is no building where the desired target temperature is 1.

**Comment by msftristew** [comment]
Also, there are exactly 100 elements in that dataset, so the proportion of each section of the graph should be 1%, when it looks like it varies from ~0.95% to ~1.05%.  This is very odd IMO, we shouldn't see that kind of variance.  Even taking floating point rounding error into account, we should at least be rounding to the nearest tenth of a percentage point or something.

**Comment by msftristew** [comment]
![screen shot 2016-01-07 at 12 41 39 pm](https://cloud.githubusercontent.com/assets/13972471/12182331/5d0e0854-b53c-11e5-9b95-d3e18ef2e449.png)

Here's another example. This dataframe has 3 records: one with i=1, one with i=2, one with i=3.  So obviously there should be three slices of the pie, which are labeled [1,2,3], and which are equally sized.  There seem to be two distinct issues with the two visualizations we see here:

1. The labeling is being done in terms of the index into the dataframe.  You want to label based on X-axis values.

2. The magnitude of the slices should be determined by a record count after grouping the values on X.

**Comment by msftristew** [comment]
#107 will fix pies. I'm not closing this yet, I want to verify that there are no more inaccurate visualizations for other graphs.

**Comment by aggFTW** [comment]
Thanks for looking at this @msftristew. I had noticed bugs on pie graphs but hadn't put my finger on what the wrong thing was. I believe pie graphs were the only ones that were wrong. Feel free to post any other things you find.

**Comment by msftristew** [comment]
BTW, as long as we've made this change, it might be interesting to investigate creating multi-dimensional pie graphs. For example if you had a dataframe with dimensions "gender" and "state", you might create a pie graph on both dimensions so you could compare the number of women in Washington to the number of men in Illinois, etc.  This is complicated from an interface perspective but the plumbing is there.  Something to think about.

**Comment by aggFTW** [comment]
Yes :) multi series support would be great and doable for all graph types.

We can tackle it later.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Mon, Jan 11, 2016 at 12:44 PM -0800, "msftristew" <notifications@github.com<mailto:notifications@github.com>> wrote:


BTW, as long as we've made this change, it might be interesting to investigate creating multi-dimensional pie graphs. For example if you had a dataframe with dimensions "gender" and "state", you might create a pie graph on both dimensions so you could compare the number of women in Washington to the number of men in Illinois, etc. This is complicated from an interface perspective but the plumbing is there. Something to think about.

-
