### ISSUE TITLE
Improve error when credentials are not provided

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#109]
Currently, when you fail to specify credentials in the config file, the kernel crashes. The exception (that you need to provide credentials for Livy) is visible in Jupyter's logs but it would be ideal if the kernel didn't crash and instead the error message was written to the screen.

**Comment by aggFTW** [comment]
This is true for other errors (when Livy returns 502 for example). We need to surface all of them.

**Comment by msftristew** [comment]
Good point. We already have the machinery in place to catch and display errors when Livy times out so we should leverage the same strategy for these.

**Comment by aggFTW** [comment]
Ricky, will you tackle other errors too?

**Comment by msftristew** [comment]
I haven't seen any other errors.  I did a quick test by pointing the magics to an incorrect URL and the error I got for that was sensible.

I don't know how to force Livy to return a 502 to me so I couldn't test that scenario in particular.

**Comment by aggFTW** [comment]
Just go to a cluster and shut Livy down. Gateway will return 502.
Or point it to a non-Spark cluster.

**Comment by msftristew** [comment]
Let me give it a shot

**Comment by msftristew** [comment]
The kernel doesn't crash when the gateway returns 502.  (This makes sense since we only try to connect to Livy after running the first cell.)

I am going to close this issue because I don't think any of us know of any situations where the error still happens.
