### ISSUE TITLE
Shutdown pyspark kernel doesn't gaurantee that session has been deleted 

### ISSUE THREAD

**Issue by MohamedElKamhawy** [jupyter-incubator/sparkmagic#110]
Repro Steps: 
- Open Pyspark kernel 
- Do any operation, 1+1 for example 
- shutdown it before getting the answer (while creating the SQL context & Hive one)
- SSH the cluster, you'll find the session still existing

For now, to delete it, you have to do that manually from ssh the cluster.

**Comment by msftristew** [comment]
An easy solution would be to separate the initialization of the Livy Client from the creation of the SQL context, etc.  So Livy clients would need an extra method `start()` which creates the SQL context and waits for the idle state, and then only call that after adding the client to the client manager.  I think that would fix it.

**Comment by aggFTW** [comment]
+1 on Ricky's comment. Factory would probably have to call the start method for client.

**Comment by msftristew** [comment]
I can take this if no one else is working on it
