### ISSUE TITLE
Expose only certain graph types depending on column makeup

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#117]
Apply heuristics to prevent users from choosing "nonsense" graphs, like line graphs where the Y-axis is of string type, etc.  

We are already applying a similar heuristic when the data is 1-dimensional but we should add more cases.

**Comment by aggFTW** [comment]
Can you propose the set of heuristics to apply?

**Comment by msftristew** [comment]
My understanding is that there are two sorts of column types in dataframes;

* Numeric types (intN, float, etc. -- I think boolean also?)

* String types

Right now our logic is like this:

* Get the number of columns in the dataframe. If it's greater than one, allow the user to select any graph type.  Otherwise just offer pie and table.

I propose changing the logic to be like this:

* Filter out all the string columns in the dataframe and get the number of numeric columns.  If it's greater than one, allow the user to select any graph type. Otherwise just offer pie and table.

I think this should do it.

**Comment by aggFTW** [comment]
No, line/bar/other graph types are valid even if only string types are provided.

**Comment by msftristew** [comment]
How?

**Comment by msftristew** [comment]
I see that the data widget successfully creates *some* graph when I give it two string axes, but the axes don't really make sense and the graph isn't meaningful.  Is there really a use case for this?

**Comment by aggFTW** [comment]
![ristew](https://cloud.githubusercontent.com/assets/654204/12311117/dec4cdd4-ba09-11e5-8b28-a72017aca0d4.PNG)

**Comment by msftristew** [comment]
BTW, the widget crashes if you try to aggregate a string column of Y by avg.

**Comment by aggFTW** [comment]
Great catch. Let me work on that.

**Comment by msftristew** [comment]
While having a scatter plot where the Y-axis is a string (categorical) value might make sense, these graphs don't really.  Line graphs, area graphs, and bar graphs only make sense on a numerical Y-axis.

**Comment by msftristew** [comment]
My proposal is that categorical Y-axes, there should only be 1 chart type: scatter plot (without lines connecting the dots).  Line graphs, area graphs, and bar graphs don't work.

**Comment by msftristew** [comment]
Another note: pressing the "log scale" buttons for string axes shouldn't be an option.  As it stands now the widget doesn't crash but it doesn't display any data if you choose "log scale".

**Comment by aggFTW** [comment]
![ristew](https://cloud.githubusercontent.com/assets/654204/12312204/60871540-ba12-11e5-8a5d-2a00f7545592.PNG)

**Comment by aggFTW** [comment]
Agreed that they don't make sense and scatter plots (histograms?) are better.

**Comment by msftristew** [comment]
That result looks good.

Histograms don't fit here: they're for mapping distributions of numerical X-values to frequencies.  Scatter plots will work for both categorical X- and Y-values.  

I wonder if the best solution here would be to add a new option, a checkbox marked "line", which turns on or off the line on a scatter plot.  We could have the line be off by default and you could turn it on if you really wanted it.

The log scale options should still be turned off for categorical axes.

**Comment by aggFTW** [comment]
Closing this as we will probably rely on the jupyterlab mimetype visualization framework and respective plugins in the future.
