### ISSUE TITLE
How many values should we take as a threshold to start coercing into category?

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#139]
10? 20? 50? (number of states)
It seems too error prone for now.

Maybe we shouldn't coerce into categorical at all?

According to [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/categorical.html):

```
The categorical data type is useful in the following cases:

* A string variable consisting of only a few different values. Converting such a string variable to a categorical variable will save some memory, see here. 
* The lexical order of a variable is not the same as the logical order (“one”, “two”, “three”). By converting to a categorical and specifying an order on the categories, sorting and min/max will use the logical order instead of the lexical order, see here. 
* As a signal to other python libraries that this column should be treated as a categorical variable (e.g. to use suitable statistical methods or plot types). 
```

Some thoughts about the reasons:
1. Saving memory doesn't seem to be much of a concern for this library.
2. The lexical order will help the min/max functions be correct when we group by columns when plotting.
3. The category will be important when select an X and Y axis automatically if we treat `categorical` as `O` in vegalite.
4. It also might be important if plotly (or any other library we use in the future) respects the order of categorical values.

As a workaround, the user could choose to execute 
```
%%sql -o df
SELECT * FROM table
```
and then execute something like
```
%%local
df[column_name] = df[column_name].astype('category')
df
```
herself if desired.

(cc @ellisonbg)

**Comment by msftristew** [comment]
I think we decided never to coerce into categorical?

**Comment by aggFTW** [comment]
Correct
