### ISSUE TITLE
Silence SQL queries

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#141]
Now that we support `-o` for collecting results as a dataframe, it would be nice to turn off automatic visualizations on a per-query level so that e.g. if I want to collect the results of a SQL query and visualize it in `%%local` mode, I can turn off visualizations for that query to cut down on visual noise.

**Comment by aggFTW** [comment]
I think we should always output something... If user wants to silence, maybe they can pass in a quiet `-q` flag?

**Comment by msftristew** [comment]
That's what I'm suggesting :)

**Comment by aggFTW** [comment]
Ah, got it :)
