### ISSUE TITLE
Remove pie chart option?

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#146]
Do we want to replace it with a histogram chart instead?

**Comment by msftristew** [comment]
Histograms aren't alternatives to pies. 

Pies are subsumed by bar charts but one potential issue (besides the fact that you can't make a pie if you want it) is that bar charts require manually aggregating over your data set, unlike pie charts where the aggregation and counting happens automatically.

**Comment by aggFTW** [comment]
A lot of people seem to be using them. Closing this for now.
