### ISSUE TITLE
Show progress for long running operations

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#147]
Operations like:
- Session creation
- Statement execution

Progress should:
- Be dismiss-able
- Make it clear that code has not hung

**Comment by Stibbons** [comment]
I would love to have the same visual feedback with subjob appearing under the cell, like on the databricks notebook ! I am willing to work on it !

**Comment by aggFTW** [comment]
So we have been talking about how to do this, and in order to achieve it, we need two pieces:

1. Livy has to send statement execution progress and subjob information when querying /session/ID/statement/ID. We will be working on this in the future, but no ETA yet.
2. A GUI on the notebook that refreshes based on the latest Livy information while the statement is running. We were thinking about ipywidgets for this, but we hit some difficulties when we tried: https://github.com/ipython/ipywidgets/issues/642
It seems it was fixed since though.

For now, we could start by prototyping the GUI part. An idea could be to have `Command` display a widget that is updated every time you get the statement information with some dummy information (e.g. increasing int) until we get the Livy part done: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/command.py#L50

Feel free to play with the code yourself and I can guide any way you need!

**Comment by Stibbons** [comment]
Ok, I'll look at Livy if there are missing parts in it.

I really love to "inject" from the Spark Web UI several parts: the progress bars of the complete job and the subjobs, also the DAG graph (or link to this page), and more important, the Event TImeline which i find very cool ! But for a start, I'll start with a simple overall progress bar.

I'll see what I can do

**Comment by aggFTW** [comment]
All of the scenarios you describe are very cool indeed!

On the Livy side of things, I would suggest creating a JIRA at https://issues.cloudera.org/projects/LIVY/issues in order to discuss what the best approach might be. Different resource managers might imply different approaches. @tc0312 can be of help here.

**Comment by Stibbons** [comment]
Good idea.

**Comment by tps-supership** [comment]
Any update on this? I see there are progress reports within the api now:
`/sessions/{session_id}/statements`
 returns a Json containing the statements and their progress

**Comment by aggFTW** [comment]
No progress on our side on this, but would be a cool community contribution!

**Comment by tps-supership** [comment]
We are running this patch successfully on our platform, but integration tests for the pull request fail on unrelated cases.
Anything i can provide here?

**Comment by gsemet** [comment]
Would be so cool to finally integrate it !

**Comment by kratika2210** [comment]
Is there some ETA on this feature? Would be great to have this.

**Comment by lucasdurand** [comment]
Yes please!

**Comment by itamarst** [comment]
This is done, I believe.
