### ISSUE TITLE
Handle magic detection better

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#151]
If there's a comment in the first line, we assume we want to execute the code below verbatim (send to IPython).

Could we use IPython magics mechanism itself to handle our magics?

**Comment by msftristew** [comment]
Some thoughts:

* We could implement a simple parser for comments to filter out any comments/empty lines at the beginning of the cell.  We would want this to work for comments not only in Python but also in Scala (eventually R).  Python comments are generally simple (`#`), Scala is more complicated (`//` for line comments, `/*` for block comments).  We'd need to beef up our parser.  Open question: are there other kinds of text besides whitespace and comments that people generally expect to be able to go before magics?

* We could *probably* use IPython's parser for magics to handle ours (haven't seen the interface myself), but it won't work with any language but Python.  I'd argue that we shouldn't implement it if we can't have the same feature for all languages.

**Comment by msftristew** [comment]
BTW, how is error reporting when you put a magic at the bottom of a code cell?  Like this:

    1+1
    %config -f { "a":"b" }

My understanding is that the error message is a little confusing.

**Comment by msftristew** [comment]
@aggFTW Is this issue resolved?

**Comment by aggFTW** [comment]
Yes. We'l ljust adhere to IPYthon's comments handling. Cell magics must not start with comments.
