### ISSUE TITLE
Multiple requests to add_session in sparkcontroller can end up leaking sessions

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#159]
Because the session is created before name duplication exists, session can be leaked. Even if we checked for name duplication before we created the session, there could be a race condition

**Comment by aggFTW** [comment]
This was found when clicking Create Session in the widgets I'm using multiple times in a row and creating multiple sessions, but the manager only ends up saving one session.

**Comment by msftristew** [comment]
I'm confused about the issue here.  When you're using the widgets, do multiple methods get called on the sparkcontroller concurrently?  *Nothing* in this library is threadsafe.

**Comment by aggFTW** [comment]
Now that you mention it, I'm not sure if the button events fire events concurrently or not... I was assuming that they do fire concurrently

I know nothing is threadsafe :)

**Comment by aggFTW** [comment]
https://github.com/ipython/ipywidgets/issues/349

**Comment by msftristew** [comment]
You should look into it.  From what you described I would say that there are two possibilities of what's happening here:

1. When you press the "Create Session" button the second time, the first create-session action is interrupted, and it tries to create a second session with the same name.  This case is probably resolvable on our end, we'll just have to do some digging.  (Note that generally we don't design sparkcontroller methods as if they can be interrupted, so we might want to review the code again to make sure there are no other similar race conditions.)

2.  When you press the "Create Session" button the second time, it runs it concurrently along with the first request.  If this is the case, then we should do some queuing or something on the widgets side to make sure that only one thread is mutating the sparkcontroller at a time.
