### ISSUE TITLE
Add configuration to turn off HiveContext, use plain SqlContext instead

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#171]
See title. User should be able to flip a configuration to use a plain SqlContext instead of a full HiveContext.  The context should have the same name (sqlContext) regardless of which kind of context you're using, so the switch would be transparent for the user.

**Comment by tc0312** [comment]
Related change in Livy: [LIVY-94. SQLContext/HiveContext is not available in Interpreter](cloudera/livy/pull/132)

**Comment by msftristew** [comment]
Is my understanding correct that this change automatically creates a SQLContext in Livy interactive sessions and that Livy itself would have a configuration to choose between HiveContext and SqlContext?

**Comment by linchan-ms** [comment]
No. Actually it completely skips the creation of sqlContext variable. That responsibility is completely shifted to Livy. Livy has the config to say you want only SQLContext or you want HiveContext. I guess you could say that with livy 0.3 and this, this issue is resolved.

**Comment by aggFTW** [comment]
Solved by Livy.
