### ISSUE TITLE
Report execution times for cell executions

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#181]
Actually, we can probably go one step further and report the execution time for _everything_, including all code cells in any language.  

Open questions:
- Where does this info get reported?  How does the UI look?

**Comment by 1Shibol** [comment]
Perhaps consider the following extension: 

http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/execute_time/readme.html

**Comment by aggFTW** [comment]
Thanks @1Shibol! 😄 

We were thinking of reporting execution time from Spark's perspective, flowing from Livy itself, and not from the client. This is a good alternative in the meantime for users who want cell execution times now.

**Comment by aggFTW** [comment]
Closing since we don't believe Sparkmagic should be doing this itself.
