### ISSUE TITLE
Display fatal error and delete session if sql context creation errors out

### ISSUE THREAD

**Issue by MohamedElKamhawy** [jupyter-incubator/sparkmagic#191]

**Comment by MohamedElKamhawy** [comment]
Example: I have created a cluster and then get an error while running my first Spark code. 
`<console>:14: error: not found: value sqlContext
sqlContext.sql("""SELECT clientid, querytime, deviceplatform, querydwelltime 
^`

In LivySession class, we are executing the command of creating sqlContext without checking the output from the execute method.

**Comment by msftristew** [comment]
We agree that it should be a fatal error if SQL context creation fails?

**Comment by aggFTW** [comment]
Yes
