### ISSUE TITLE
CREATE TABLE without IF NOT EXISTS fails

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#200]
%%sql  
     CREATE TABLE bar (
       baz int
     )

This fails with this error:

     An error occurred while calling o56.sql.
: org.apache.spark.sql.execution.QueryExecutionException: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. AlreadyExistsException(message:Table bar already exists)

The SQL query actually gets executed twice (once to figure out the dataframe has no data, and another time to get the column names).  But it fails to execute the query the second time because the table was created the first time.

You can work around this issue by doing

    %%sql
    CREATE TABLE IF NOT EXISTS bar (...

... but it would be ideal if we could avoid this altogether.

I do not know if it's possible to do queries like `INSERT` in Hive, but this would also affect that by running the `INSERT` query twice.

**Comment by msftristew** [comment]
How important is it that we run each SQL query twice to get the column names? Seems kind of brittle to me.

**Comment by aggFTW** [comment]
Good point... It's very brittle indeed. What would the alternative be? A "No results"?

**Comment by msftristew** [comment]
I think so.  So the autoviz widget would just be a little text box saying "No results" if the result dataframe is empty.

**Comment by aggFTW** [comment]
Sounds good.
