### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#202]
Let's define the schema for each event here and team up on instrumenting the code.

Session Creation (agg)
- [x] SessionCreationStart
* (InstanceId, EventName, Timestamp, SessionGuid, LivyKind)
- [x] SessionCreationEnd
* (InstanceId, EventName, Timestamp, SessionGuid, LivyKind, SessionId, Status, Success, ExceptionType, ExceptionMessage)

Session Deletion (agg)
- [x] SessionDeletionStart
* (InstanceId, EventName, Timestamp, SessionGuid, LivyKind, SessionId, Status)
- [x] SessionDeletionEnd
* (InstanceId, EventName, Timestamp, SessionGuid, LivyKind, SessionId, Status, Success, ExceptionType, ExceptionMessage)

Statement Execution (Rs)
- [x] StatementExecutionStart 
* (InstanceId, EventName, Timestamp, SessionGuid, LivyKind, SessionId, StatementGuid)
- [x] StatementExecutionEnd 
* (InstanceId, EventName, Timestamp, SessionGuid, LivyKind, SessionId, StatementGuid, StatementId, Success, ExceptionType, ExceptionMessage)

Sql Execution (rs)
- [x] SqlExecutionStart 
* (InstanceId, EventName, Timestamp, SessionGuid, LivyKind, SessionId, SqlGuid)
- [x] SqlExecutionEnd
* (InstanceId, EventName, Timestamp, SessionGuid, LivyKind, SessionId, SqlGuid, StatementGuid, Success, ExceptionType, ExceptionMessage)

Magic Execution (rs)
- [x] MagicExecutionStart 
* (InstanceId, EventName, Timestamp, MagicName, LivyKind, MagicGuid)
- [x] MagicExecutionEnd
* (InstanceId, EventName, Timestamp, MagicName, LivyKind, MagicGuid, Success, ExceptionType, ExceptionMessage)

Library loaded (agg)
- [x] LibraryLoaded
* (InstanceId, EventName, Timestamp)

Autoviz (rs)
- [x] AutovizGraphRendered
* (InstanceId, EventName, Timestamp, GraphType)

**Comment by msftristew** [comment]
Pretty nifty checklist feature that Github has

**Comment by msftristew** [comment]
Should we have a separate event for failure to execute a statement?

**Comment by msftristew** [comment]
Looks like all events start with the columns "InstanceId, EventName, Timestamp"

**Comment by aggFTW** [comment]
On failure to execute a statement, shouldn't we just write the result of the execution?
Or what did you mean by failure? Are there different types of failures?

**Comment by msftristew** [comment]
Failure to execute a statement is when an exception is thrown so no actual result is returned to the user

**Comment by msftristew** [comment]
e.g. unknown statement output status from Livy, http client throwing

**Comment by aggFTW** [comment]
So we are done with the list. As soon as you submit your PRs, we should be good to go, instrumentation wise.
