### ISSUE TITLE
Value Error in Caching large data using SparkMagic

### ISSUE THREAD

**Issue by MengyingLi** [jupyter-incubator/sparkmagic#225]
Value error will be thrown when caching the data (400+ G) by doing the count:
```
from pyspark.storagelevel import StorageLevel
machineAppsView.persist(StorageLevel.MEMORY_ONLY_SER)
from time import time
t0 = time()
machineAppsView_count = machineAppsView.count()
tt = time() - t0
print "count in {} seconds".format(round(tt,3))
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-f180740f25cb> in <module>()
----> 1 get_ipython().run_cell_magic(u'spark', u'', u'from time import time\nt0 = time()\nmachineAppsView_count = machineAppsView.count()\ntt = time() - t0\nprint "count in {} seconds".format(round(tt,3))\n ')

/usr/bin/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2291             magic_arg_s = self.var_expand(line, stack_depth)
   2292             with self.builtin_trap:
-> 2293                 result = fn(magic_arg_s, cell)
   2294             return result
   2295 

<decorator-gen-120> in spark(self, line, cell, local_ns)

/usr/bin/anaconda/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/var/lib/sparkmagiclibs/sparkmagic-publicpreview0.3/remotespark/kernels/kernelmagics.pyc in spark(self, line, cell, local_ns)
    174     def spark(self, line, cell="", local_ns=None):
    175         if self._do_not_call_start_session(""):
--> 176             (success, out) = self.spark_controller.run_command(Command(cell))
    177             if success:
    178                 self.ipython_display.write(out)

/var/lib/sparkmagiclibs/sparkmagic-publicpreview0.3/remotespark/livyclientlib/sparkcontroller.pyc in run_command(self, command, client_name)
     25     def run_command(self, command, client_name=None):
     26         session_to_use = self.get_session_by_name_or_default(client_name)
---> 27         return command.execute(session_to_use)
     28 
     29     def run_sqlquery(self, sqlquery, client_name=None):

/var/lib/sparkmagiclibs/sparkmagic-publicpreview0.3/remotespark/livyclientlib/command.pyc in execute(self, session)
     28             response = session.http_client.post_statement(session.id, data)
     29             statement_id = response['id']
---> 30             output = self._get_statement_output(session, statement_id)
     31         except Exception as e:
     32             self._spark_events.emit_statement_execution_end_event(session.guid, session.kind, session.id,

/var/lib/sparkmagiclibs/sparkmagic-publicpreview0.3/remotespark/livyclientlib/command.pyc in _get_statement_output(self, session, statement_id)
     43         out = ""
     44         while statement_running:
---> 45             statement = session.http_client.get_statement(session.id, statement_id)
     46             status = statement["state"]
     47 

/var/lib/sparkmagiclibs/sparkmagic-publicpreview0.3/remotespark/livyclientlib/livyreliablehttpclient.pyc in get_statement(self, session_id, statement_id)
     22 
     23     def get_statement(self, session_id, statement_id):
---> 24         return self._http_client.get(self._statement_url(session_id, statement_id), [200]).json()
     25 
     26     def get_sessions(self):

/var/lib/sparkmagiclibs/sparkmagic-publicpreview0.3/remotespark/livyclientlib/reliablehttpclient.pyc in get(self, relative_url, accepted_status_codes)
     31     def get(self, relative_url, accepted_status_codes):
     32         """Sends a get request. Returns a response."""
---> 33         return self._send_request(relative_url, accepted_status_codes, requests.get)
     34 
     35     def post(self, relative_url, accepted_status_codes, data):

/var/lib/sparkmagiclibs/sparkmagic-publicpreview0.3/remotespark/livyclientlib/reliablehttpclient.pyc in _send_request(self, relative_url, accepted_status_codes, function, data)
     42 
     43     def _send_request(self, relative_url, accepted_status_codes, function, data=None):
---> 44         return self._send_request_helper(self.compose_url(relative_url), accepted_status_codes, function, data, 0)
     45 
     46     def _send_request_helper(self, url, accepted_status_codes, function, data, retry_count):

/var/lib/sparkmagiclibs/sparkmagic-publicpreview0.3/remotespark/livyclientlib/reliablehttpclient.pyc in _send_request_helper(self, url, accepted_status_codes, function, data, retry_count)
     76                 else:
     77                     raise ValueError("Invalid status code '{}' or error '{}' from {}"
---> 78                                      .format(status, error, url))
     79             return r

ValueError: Invalid status code '500' or error 'False' from http://hn0-diispa.w5hqrdtznfhupm3m2urayuj20b.gx.internal.cloudapp.net:8998/sessions/3/statements/4

**Comment by msftristew** [comment]
This is a Livy bug, is it not?

**Comment by msftristew** [comment]
Closing because this seems to have nothing to do with Sparkmagic

**Comment by aggFTW** [comment]
Thanks for reporting @MengyingLi. This status code of '500' means that Livy errored out when executing the request. As @msftristew mentioned, this has nothing to do with sparkmagic itself, so it's good that he closed it.

**Comment by aaronsteers** [comment]
I've run into the same error message and have not found any other resources online that reference this error message. Is there any known workaround using Spark SQL or Jupyter, or else can someone provide a reference to the related Livy fix? (I'm admittedly new to spark and not at all familiar with Livy.)

**Comment by aggFTW** [comment]
You are doing a cache on a big dataset and getting 500 back from Livy session?

What is most probably happening behind the scenes is that your spark session is running out of memory and the spark app errors out. Can you describe your Spark and Livy installation? Can you describe your dataset?

Look at your Spark logs :smiley:
