### ISSUE TITLE
Improve output of %%info

### ISSUE THREAD

**Issue by tc0312** [jupyter-incubator/sparkmagic#230]
Might want to use [this ](https://ipython.org/ipython-doc/3/config/integrating.html) to show a HTML table.

**Comment by msftristew** [comment]
You could add a small `SessionCollection` class which just wraps a list of `LivySession`s that has a `_repr_html_` method that generates the table.

The current model which has a `__str__` method on the `LivySession` is pretty silly, and we should move away from it.

**Comment by msftristew** [comment]
Going to work on this.
