### ISSUE TITLE
Error: has there been an update?

### ISSUE THREAD

**Issue by yaksoo39** [jupyter-incubator/sparkmagic#265]
We use the Azure Spark tutorial ( https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apache-spark-machine-learning-mllib-ipython/ )  and have successfully completed before with our students.  

In one of the steps we issue the following command:

%%sql -q -o true_positive
SELECT count(*) AS cnt FROM Predictions WHERE prediction = 0 AND results = 'Fail'

%%sql -q -o false_positive
SELECT count(*) AS cnt FROM Predictions WHERE prediction = 0 AND (results = 'Pass' OR results = 'Pass w/ Conditions')

%%sql -q -o true_negative
SELECT count(*) AS cnt FROM Predictions WHERE prediction = 1 AND results = 'Fail'

%%sql -q -o false_negative
SELECT count(*) AS cnt FROM Predictions WHERE prediction = 1 AND (results = 'Pass' OR results = 'Pass w/ Conditions') 

Recently, we have encountered the following error:

An internal error was encountered.
Please file an issue at https://github.com/jupyter-incubator/sparkmagic
Error:
u"cannot recognize input near '%' 'sql' '-' in expression specification; line 3 pos 1"
Traceback (most recent call last):
  File "/mnt/resource/hadoop/yarn/local/usercache/spark/appcache/application_1466733212610_0001/container_e02_1466733212610_0001_01_000001/tmp/6037623361340072321", line 90, in execute
    exec code in global_dict
  File "<stdin>", line 10, in <module>
  File "/usr/hdp/current/spark-client/python/pyspark/sql/context.py", line 580, in sql
    return DataFrame(self._ssql_ctx.sql(sqlQuery), self)
  File "/usr/hdp/current/spark-client/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/hdp/current/spark-client/python/pyspark/sql/utils.py", line 51, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
AnalysisException: u"cannot recognize input near '%' 'sql' '-' in expression specification; line 3 pos 1"

**Comment by aggFTW** [comment]
Are all the sql commands in their own cells? You can only have one sql magic command per cell.

SQL Magics are cell magics.

**Comment by yaksoo39** [comment]
Wow, thanks for your super fast response.  That did the trick, however, I am still a bit confused.  I could have sworn that I was having students do all the commands together previously.  Has there been a recent change?  Even as I ask, I realize the answer is probably no, since as you say, sql magic are cell magic.

 

In any case, thank you very much!!!

 

Henry Park

The Big Link

Mobile: 010-5768-0115

**Comment by aggFTW** [comment]
No changes for a while. No worries. Glad it's working now =)
