### ISSUE TITLE
how to add jar?

### ISSUE THREAD

**Issue by cycorey** [jupyter-incubator/sparkmagic#268]
how to add jar from hdfs?
how to add jar from local folder?
how to add jar from maven?

I don't found the doc, so if who can tell me, I would like to add it to sparkmagic wiki.

Thanks!

**Comment by aggFTW** [comment]
You can use the `%%configure` magic as well as SparkConf parameters to configure the notebook.

So, it would look something like this:
```
%%configure -f 
{
    "conf": {
        "spark.jars.packages": "com.databricks:spark-csv_2.10:1.4.0",
        "spark.executor.memory": "2g",
        "spark.driver.memory": "4g",
        "spark.driver.cores": "2",
        "spark.executor.cores": "2",
        "spark.executor.instances": "32"
    }
} 
```

You can get the list of configurations you can use by going to:
* http://spark.apache.org/docs/latest/configuration.html
* http://spark.apache.org/docs/latest/running-on-yarn.html

You can complement the information I just gave you with:
https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apache-spark-jupyter-notebook-use-external-packages/

Feel free to add this to the wiki :smiley:
