### ISSUE TITLE
"Yarn Application ID", "Spark UI", "Driver Log" are empty, when I run %%info magic

### ISSUE THREAD

**Issue by prabhu1984** [jupyter-incubator/sparkmagic#269]
Hi, first, thanks for open sourcing this wonderful project. It's working great.

A small issue on my notebook, somehow, it's not showing "Yarn Application ID", "Spark UI", "Driver Log" when I run %%info magic
![sparkmagic](https://cloud.githubusercontent.com/assets/16215481/16610668/8df4fbb8-4311-11e6-9e49-9d5f4aba4c44.png)
. I'm running my job on yarn-cluster mode. 

Attached the snapshot. Please help me to understand what went wrong, why these details are not showing. How spark magic is getting these results to show on notebook, because when I manually curl livy, it's showing only below result.
{
    "from": 0, 
    "sessions": [
        {
            "id": 6, 
            "kind": "spark", 
            "log": [], 
            "owner": null, 
            "proxyUser": null, 
            "state": "idle"
        }
    ], 
    "total": 1
}

**Comment by aggFTW** [comment]
What version of Livy are you using? Where did you get it from? I'm guessing you installed Livy yourself in a Spark cluster of yours?

We modified Livy to provide that information in Microsoft HDInsight Spark clusters in a private fork we have of Livy and we are currently working to push those changes back to the main Livy branch.

**Comment by prabhu1984** [comment]
Thanks for your reply!

I built Livy from cloudera/livy.git (0.3.0-Snapshot) and running on Yarn. From summit (Praveen/Maxim sessions), I got to know lot of things and implement everything from Jupyterhub, Jupyter, SparkMagic, Livy and all were working great. I'm also looking for addition info like how to get YarnApplicationId, SparkUI, DriverLog, etc and, also looking for how Livy got integrated with Zookeeper for HA. Is enhanced/improved Livy version available in any git, if yes, please refer, it would be very helpful! Thanks!

Thanks
Prabhu

**Comment by aggFTW** [comment]
Not at the moment. As I mentioned, we are working on pushing the changes to the official repo.

Glad you are finding the projects useful!

**Comment by aggFTW** [comment]
Just FYI (not recommended you take a dependency on it), here's the Livy fork: https://github.com/hdinsight/livy/tree/master

**Comment by prabhu1984** [comment]
Thank you so much for sharing this one. Appreciate it!

Let me check it out.
