### ISSUE TITLE
Multi Livy Support

### ISSUE THREAD

**Issue by prabhu1984** [jupyter-incubator/sparkmagic#278]
Hi,

Spark magic currently supports connectivity to single livy instance. 

Is there a way I can configure multiple livy instances (for multiple hadoop clusters) on same config.json? Please let us know.

i.e 

  "kernel_python_credentials" : {
    "username": "",
    "password": "",
    "cluster": "hadoop-dev",
    "url": "http://livy-dev.example.com:8998"
  },

  "kernel_scala_credentials" : {
    "username": "",
    "password": "",
    "cluster": "hadoop-dev",
    "url": "http://livy-dev.example.com:8998"
  },

  "kernel_python_credentials" : {
    "username": "",
    "password": "",
    "cluster": "hadoop-qa",
    "url": "http://livy-qa.example.com:8998"
  },

  "kernel_scala_credentials" : {
    "username": "",
    "password": "",
    "cluster": "hadoop-qa",
    "url": "http://livy-qa.example.com:8998"
  },

  "kernel_python_credentials" : {
    "username": "",
    "password": "",
    "cluster": "hadoop-prod",
    "url": "http://livy-prod.example.com:8998"
  },

  "kernel_scala_credentials" : {
    "username": "",
    "password": "",
    "cluster": "hadoop-prod",
    "url": "http://livy-prod.example.com:8998"
  },

**Comment by linchan-ms** [comment]
Currently it is not supported. To make it really work, not just we have to allow multiple livy servers in conf file, but have to expose the choice of livy servers to every notebook. That functionality is not currently there.

**Comment by aggFTW** [comment]
How would you like to choose which cluster to use?

**Comment by prabhu1984** [comment]
Hi @linchan-ms / @aggFTW ,

I'm thinking of enabling multi-livy (i.e. multi cluster) support through one of the below three options. Can you please let me know your thoughts which is the efficient, right and easy to implement? Or, let me know, if you think any other option. Thanks!

Option1: Enabling different notebook kernel for each cluster/livy instance as below

![Current - Jupyter - Option1](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/Current%20-%20Jupyter%20-%20Option1.png?raw=true)
{vs}
![Proposed - Jupyter - Option1](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/Proposed%20-%20Jupyter%20-%20Option1.png?raw=true)

Option2: Enabling different %%sparkmagic for each cluster/livy instance as below

![Current - Jupyter - Option2](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/Current%20-%20Jupyter%20-%20Option2.png?raw=true)
{vs}
![Proposed - Jupyter - Option2](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/Proposed%20-%20Jupyter%20-%20Option2.png?raw=true)

Option3: Setting Livy URL by %%configure while starting the notebook as below

![Proposed - Jupyter - Option3](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/Proposed%20-%20Jupyter%20-%20Option3.png?raw=true)

**Comment by aggFTW** [comment]
I would say that dedicated kernel and dedicated magic options are not easy to generalize for users. How would a user define the n+1 environment without modifying code?

As of today, we have a [serverextension](https://github.com/jupyter-incubator/sparkmagic#server-extension-api) that allows you to [submit a cluster endpoint via a magic](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/serverextension/handlers.py#L53).

You could leverage this magic called [`_do_not_call_change_endpoint`](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/kernels/kernelmagics.py#L338) and put it at the top of your notebooks.

Would that work for you?

**Comment by linchan-ms** [comment]
I agree with @aggFTW. The serverextension could be more dynamic. For usability, you can add code to print out the current endpoint in %%info magic.

**Comment by aggFTW** [comment]
If you do add code to print the endpoint information via the `%%info` magic, please put it behind a configuration parameter so that users that do not want to see endpoint information can disable it.

**Comment by prabhu1984** [comment]
Thanks for the details. I was not aware that spark magic already has multiple endpoints support feature. 

Just read this one: //https://github.com/jupyter-incubator/sparkmagic#architecture: Support for multiple endpoints; you can use a single notebook to start multiple Spark jobs in different languages and against different remote clusters//

Can you please give me some example how to change endpoint on notebook? I couldn't find any example?

Thanks!

**Comment by aggFTW** [comment]
This is described in: https://github.com/jupyter-incubator/sparkmagic#examples

Example of the method you describe: https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Magics%20in%20IPython%20Kernel.ipynb

Notice that the magic I mentioned on my previous comment works for the kernel-based use of sparkmagic.

I think that with the above comments, one could effectively use different Livy endpoints. I'll mark this as closed.

**Comment by prabhu1984** [comment]
@aggFTW : Thank you so much. I got the required details from https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Magics%20in%20IPython%20Kernel.ipynb.
