### ISSUE TITLE
Default configurations do not work with stock Livy

### ISSUE THREAD

**Issue by waschult** [jupyter-incubator/sparkmagic#283]
Hallo,

after installing sparkmagic i've started spark 1.6.1 and livy 0.2.0. Then i started jupyter notebook and tried Spark Kernel.ipynb. The first commands %%info, %%help, %%configure are working but if i execute %%sql -o query1 i get the following error /heartbeatTimeoutinSeconds).

The code failed because of a fatal error:
    Invalid status code '500' from http://localhost:8998/sessions with error payload: "com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"heartbeatTimeoutInSecond\" (class com.cloudera.livy.server.interactive.CreateInteractiveRequest), not marked as ignorable (14 known properties: \"executorCores\", \"conf\", \"driverMemory\", \"name\", \"driverCores\", \"pyFiles\", \"archives\", \"queue\", \"kind\", \"executorMemory\", \"files\", \"jars\", \"proxyUser\", \"numExecutors\"])\n at [Source: HttpInputOverHTTP@40fe6bf7; line: 1, column: 52](through reference chain: com.cloudera.livy.server.interactive.CreateInteractiveRequest["heartbeatTimeoutInSecond"])".

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.

**Comment by linchan-ms** [comment]
This is likely a version mismatch between magic and Livy. The Livy you have doesn't have the per session heartbeat flag support yet. To workaround this problem now, open magic's config.json and set "livy_server_heartbeat_timeout_seconds" to 0. Thanks

**Comment by linchan-ms** [comment]
Or you can install an earlier version of sparkmagic (version 0.5.0 instead of 0.6.0). https://pypi.python.org/pypi/sparkmagic/0.5.0

**Comment by aggFTW** [comment]
@linchan-ms I think we should modify the default configuration so that examples work out of the box with latest Livy.

**Comment by waschult** [comment]
Thank you :)
Setting "livy_server_heartbeat_timeout_seconds" to 0 works for me. I get an Error with

%%sql -q -m sample -r 0.1 -n 500 -o query2 
SELECT * FROM hivesampletable

but okay, i've only installed livy and spark binarys and no hive. :)

So for me it's solved.

Thanks:)

**Comment by aggFTW** [comment]
Thanks @waschult. I believe that if you want to make the `sql` magic work, you could override `sqlContext` to be a `SqlContext` and not a `HiveContext`.

Lin, I'll rename this issue and assign it to you, if that's OK. Otherwise, I can work on it later.
