### ISSUE TITLE
Add ability to specify headers to Livy

### ISSUE THREAD

**Issue by hegand** [jupyter-incubator/sparkmagic#285]
I got the following error when try to connect to livy server on HDP 2.5:

HttpClientException: Invalid status code '400' from http://host:8998/sessions with error payload: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 </title>
</head>
<body>

<h2>HTTP ERROR: 400</h2>

<p>Problem accessing /sessions. Reason:
<pre>    Missing Required Header for CSRF protection.</pre></p>

<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

**Comment by hegand** [comment]
I can connect and run spark code on that livy server with curl, but I have to add X-Requested-By: user to the headers of the requests.

`curl -X GET -H "Content-Type: application/json" -H "X-Requested-By: user" http://host:8998/sessions`

**Comment by aggFTW** [comment]
How is Livy setup? This sounds like some particular security setting to your Livy setup.

Sparkmagic could add a config to modify headers for its requests (look at https://github.com/jupyter-incubator/sparkmagic/blob/959c4be13a00f5f0aff155660c592411291d0546/sparkmagic/sparkmagic/livyclientlib/livyreliablehttpclient.py#L17).

That'd be a welcomed community contribution :)

**Comment by hegand** [comment]
We use the default livy conf of HDP. I think may be this could cause the problem at core-site.xml:

```
<property>
   <name>hadoop.proxyuser.livy.groups</name>
   <value>*</value>
</property>
<property>
   <name>hadoop.proxyuser.livy.hosts</name>
   <value>*</value>
</property>
```

**Comment by hegand** [comment]
Thanks, i rewrite a little `from_endpoint(endpoint)` function at the linked file and it is working now 

`headers = {"Content-Type": "application/json", "X-Requested-By": getenv('HADOOP_USER_NAME',getlogin())}`
`return LivyReliableHttpClient(ReliableHttpClient(endpoint, headers, retry_policy))`

**Comment by addictedanshul** [comment]
How did you write this in java application?
I am running the Java application PiApp having spark job PiJob in below link.
https://github.com/cloudera/livy

The snippet I got as fix from sparkmagic is written in scala.
Is there no spark magic for java application?

**Comment by aggFTW** [comment]
There's no Java sparkmagic kernels, as Livy only supports interactive Scala, Python, and R shells.

**Comment by vidit-bhatia** [comment]
I can take this @aggFTW  if no one is working on this.

**Comment by aggFTW** [comment]
Feel free to!

**Comment by circleJ** [comment]
HI,ALL 
was this the same problem？plz give me some help
org.springframework.web.client.HttpClientErrorException: 400 Missing Required Header for CSRF protection.

**Comment by circleJ** [comment]
I cant find the link file，where is it？

**Comment by aggFTW** [comment]
What is your setup? Did you enable CSRF in livy? Is that the livy server-side error?

If so, you can add custom headers to your `~/.sparkmagic/config.json` file, as shown in the example config.json in this repo: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/example_config.json#L67
