### ISSUE TITLE
Neither SparkSession nor HiveContext/SqlContext is available

### ISSUE THREAD

**Issue by mickaelgervais** [jupyter-incubator/sparkmagic#305]
I'm trying to use SparkMagic with Livy but I'm stucked with this error:

`Neither SparkSession nor HiveContext/SqlContext is available`

I've tried to log the error from the server and I've found this message:
`<console>:14: error: not found: value sqlContext
sqlContext
^`
Any help would be appreciated!

Thanks

**Comment by linchan-ms** [comment]
Which version of Spark are you using? You can try to set “livy.repl.enableHiveContext” to true on Livy side and that might solve the problem.

Thanks
Lin

**Comment by mickaelgervais** [comment]
Hi Lin, 
Thank you for the response.
Apparently it works, but there is something I don't understand.
I'm using Ambari, the livy configuration file is formatted with spaces between key & value and I've this:
`livy.repl.enableHiveContext true`
With this configuration works;
But on a Livy Server manually install configuration file looks like this:
`livy.repl.enableHiveContext=true`

What is the format to use?

Thanks.

**Comment by linchan-ms** [comment]
How did you install Livy in Ambari? I think it is up to whoever wrote the ambari installation to determine how the mapping is translated. Ultimately, the real config should get into the livy.conf file. In that file, the config should look like livy.repl.enableHiveContext=true.

**Comment by aggFTW** [comment]
Thanks Lin! Will close it now, as it doesn't seem to be a sparkmagic issue.
