### ISSUE TITLE
Infinite run when connecting local jupyter notebook to HDInsight Cluster via sparkmagic

### ISSUE THREAD

**Issue by SG87** [jupyter-incubator/sparkmagic#312]
I have deployed a HDInsight 3.5 Spark (2.0) cluster on Microsoft Azure with the standard configurations (Location = US East, Head Nodes = D12 v2 (x2), Worker Nodes = D4 v2 (x4)). Locally I have installed sparkmagic following the steps in https://github.com/jupyter-incubator/sparkmagic/blob/master/README.md#installation and https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-spark-jupyter-notebook-install-locally and changed the config.json file. When starting jupyter notebook I can chose the PySpark kernel. Even tough I get the message that the kernel is ready, when I try to execute a simple statement (e.g. t = 4), the kernel starts to run infinitely. Could you provide possible solution(s)?

**Comment by aggFTW** [comment]
Only thing that comes to mind is that the `config.json` file is not correct. If my cluster were `https://sparkmagic.azurehdinsight.net`, then the connection to it would be `https://sparkmagic.azurehdinsight.net/livy`. Make sure username and password are also correct.
