### ISSUE TITLE
Handle "waiting" status form Livy

### ISSUE THREAD

**Issue by 1Shibol** [jupyter-incubator/sparkmagic#317]
Hello, 

Bumped into an issue with the latest Livy version:

- Livy version 0.3 (built from master)
- SparkMagic version 0.9.3

In **livyclintlib/command.py**, when checking the statement status:
`if status == u"running":`

Currently, the "else" clause assumes that there is an output, which is not the case of "waiting" state, thus throwing an error.

Shouldn't "waiting" state be treated just like "running" state?

**Comment by aggFTW** [comment]
@tc0312 @linchan-ms

**Comment by aggFTW** [comment]
Release 0.10.1 is out at https://pypi.python.org/pypi/sparkmagic/0.10.1
