### ISSUE TITLE
How can I get spark data frame to --output to matplot locally

### ISSUE THREAD

**Issue by prabhu1984** [jupyter-incubator/sparkmagic#318]
Hi @aggFTW,

A quick question. How can I get spark data frame to --output to marplot locally?

Example: We can get sql output from below query into df_hvac and can apply panda transformation locally. 
```
%%spark -c sql -o df_hvac --maxrows 10
SELECT * FROM hivesampletable

df_hvac.head()
```

Similarly, how to get python data frame to access locally.
```
%%spark -o df_hvac --maxrows 10
numbers = sc.parallelize([1, 2, 3, 4])

df_hvac.head()
```

I'm getting below error.

%%spark -o df_numbers
sc.parallelize([1, 2, 3, 4])
ParallelCollectionRDD[20] at parallelize at PythonRDD.scala:423

print(df_numbers)
NameErrorTraceback (most recent call last)
<ipython-input-9-63e4698d74a6> in <module>()
----> 1 print(df_numbers)
NameError: name 'df_numbers' is not defined

**Comment by aggFTW** [comment]
You will have to register the dataframe as a table and then query via the `%%sql` magic to use the `--output` mechanism. `--output` is not implemented for regular spark code and only works for the SQL magic.

**Comment by prabhu1984** [comment]
Thanks @aggFTW!
