### ISSUE TITLE
SQL output is truncated because of show command

### ISSUE THREAD

**Issue by prabhu1984** [jupyter-incubator/sparkmagic#319]
If SQL output field is long, then it's currently getting truncated and showing in table format because we are using ".show()" instead of ".take() or .collect()".

Output is truncated:
![Output is truncated](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/Sparkmagic%20-%20Output%20is%20truncated.png?raw=true)

But, take() or collect() wont return column name. So, we need to modify the output part to get column name and use take() or collect() not to truncate the data on output.

@aggFTW, let me know your thoughts.

**Comment by aggFTW** [comment]
Please change pandas' max_colwidth as indicated on this page:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.set_option.html

**Comment by prabhu1984** [comment]
Hi @aggFTW,

If I run scala/python spark commands, then I can use `show(n,truncate)` to control column width truncation.

Example:
```
hiveContext.sql("select * from table").show(n=10,**_truncate=False_**)
```

But, my question is about '%%sql' magic. In %%sql magic, how can I mention not to truncate the columns? 

I'm thinking of introducing -t boolean in addition to `-o,-q,-m,-n,-r` to control truncation. 

Please let me know your thoughts to achieve the easiest way for my req not to truncate the field. Thanks!

**Comment by aggFTW** [comment]
The `sql` magic uses pandas representation to display the table format you see. So, please modify pandas' `max_colwidth` to some higher value. You can do so by executing:

```
%%local
pd.set_option('display.max_colwidth', 100)
```

**Comment by prabhu1984** [comment]
👍 

On Jan 11, 2017, at 5:12 PM, Alejandro Guerrero Gonzalez <notifications@github.com> wrote:

The sql magic uses pandas representation to display the table format you see. So, please modify pandas' max_colwidth to some higher value. You can do so by executing:

%%local
pd.set_option('display.max_colwidth', 100)

**Comment by rokity** [comment]
> The `sql` magic uses pandas representation to display the table format you see. So, please modify pandas' `max_colwidth` to some higher value. You can do so by executing:
> 
> ```
> %%local
> import pandas as pd
> pd.set_option('display.max_colwidth', 100)
> ```

Not work for me on Glue 4.0 notebook. If I use %%sql not with pandas.

**Comment by rokity** [comment]
The only solution that it works on Glue 4.0 notebook it's this.

> Hi @aggFTW,
> 
> If I run scala/python spark commands, then I can use `show(n,truncate)` to control column width truncation.
> 
> Example:
> 
> ```
> hiveContext.sql("select * from table").show(n=10,truncate=False)
> ```
> 
> But, my question is about `%%sql` magic. In `%%sql` magic, how can I mention not to truncate the columns?
> 
> I'm thinking of introducing `-t` boolean in addition to `-o,-q,-m,-n,-r` to control truncation.
> 
> Please let me know your thoughts to achieve the easiest way for my req not to truncate the field. Thanks!

**Comment by cvargas-xbrein** [comment]
please , add more function to spark magic 👌.😪
