### ISSUE TITLE
[bug] matplotlib is not plotting variables from livy

### ISSUE THREAD

**Issue by OferE** [jupyter-incubator/sparkmagic#322]
using sparkmagic 0.5.0 and working with pyspar 1.6.2

i'm trying to plot some variables defined in my jupyter - that run on the livy.

by adding 
%matplotlib inline
i can plot variables defined in the current cell.
But i am getting NameError if i try to plot variables in previous cells defined in the livy machine.

Alternatively - if i remove the %matplotlib inline - i am getting no display error (probably since sparkmagic tries to run it on the machine that has livy.

Is there a way to take data collected from RDD (and therefore most be defined in the livy) and plot it in jupyter???

**Comment by aggFTW** [comment]
You need to create a Spark dataframe, register it as a table, and then use the `%%sql --output my_var` command to have a `my_var` on the `%%local` context, in which matplotlib and any other visualization libraries will work.

This is shown in the example notebooks:
https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Pyspark%20Kernel.ipynb

**Comment by edoardovivo** [comment]
Hello,

My apologies for commenting on a closed issue, but I'm having a similar problem, namely the ouput of a bunch of analytics steps is basically a list, that I want to plot. I cannot do it directly from livy, so the solution is, as you said, to create a spark dataframe and then import it to the ``%%local`` context. 

This works fine. However, it seems rather cumbersome, isn't it? Isn't there a way to import objects other that dataframes to the local context?

Thank you in advance,
Edoardo

**Comment by aggFTW** [comment]
You can now import dataframes directly without registering them as a table and using sql. Look for instructions via the `%%help` magic and execute via the  `%%spark` magic.

It is cumbersome, which is unfortunate... There's no easy way to bring in lists though... The things sparkmagic sends to livy and livy sends to sparkmagic are all text-based. So we would have to send over HTTP the text representation of the objects you want to send back to the local context. Lists of integers and other native types would work fine, but if a user creates a list of user-defined objects, the mechanism would break. I don't currently know how to create a good UX with these caveats. Do you have any ideas?
