### ISSUE TITLE
Issue with basic SELECT/or JSON file

### ISSUE THREAD

**Issue by daithang1111** [jupyter-incubator/sparkmagic#334]
Hi,
Running a simple PySpark command in SparkMagic:
%%sql
SELECT 1, 2, 3

causes the Error: Cannot parse object as JSON: '['b\'{"1":1,"2":2,"3":3}\'']'
This same error occurs when loading a simple JSON file with content `{"name":"test"}`:

CREATE TEMPORARY TABLE Test
USING org.apache.spark.sql.json
OPTIONS (path '/test.json')

-Per checking the code in sparkmagic/livyclientlib/sqlquery.py, we think that this line of code:
 command = u'for {} in {}: print({})'.format(constants.LONG_RANDOM_VARIABLE_NAME,
                                                    command,
                                                    print_command)

causes the problem because it adds the 'b' in front of text and parsing text trigger exception.

Any idea how to fix this?

PS: scala works fine.

Thanks!

**Comment by aggFTW** [comment]
I'm unable to repro with:

```
%%sql
SELECT 1, 2, 3
```

What sparkmagic/livy/spark versions are you under?

**Comment by daithang1111** [comment]
Thanks.
 It is Livy 0.4.0 (maven 0.4.0-SNAPSHOT), Spark 2.1.0 (running under DC/OS Mesos), and the latest Sparkmagic installed via pip install under Ubuntu 14.04.

**Comment by aggFTW** [comment]
What python version are you using? I don't quite understand where that b is coming from. What's the output from Livy? I don't think we have tested sparkmagic with Livy 0.4.0. We are using 0.3.0.

**Comment by daithang1111** [comment]
It's python 3.5. The 'b' is appended to a str from print(str.encode("utf-8")) and it causes Json Parser fail. We may try Livy 0.3.0 and see if the problem still persists.

**Comment by aggFTW** [comment]
We haven't tried it with python 3.5 either. We only test with 2.7 and 3.3 atm. The b might come from differences there.

**Comment by aggFTW** [comment]
If you can repro with tested versions, please let us know.
If you want to add compatibility with other versions, please submit a PR :)

Closing for now.

**Comment by daithang1111** [comment]
FYI, we have the same issue with python 2 or livy 3. We resolved the issue by commenting out these code from livyclientlib/sqlquery.py:
```
# Unicode support has improved in Python 3 so we don't need to encode.
#if encode_result:
            #print_command = '{}.encode("{}")'.format(constants.LONG_RANDOM_VARIABLE_NAME,
                                                     #conf.pyspark_dataframe_encoding())
#else:
        print_command = constants.LONG_RANDOM_VARIABLE_NAME
```
Be default encode_result is set to True, which should be a False otherwise it will run str.encode('utf-8') which will append 'b' in front of str.

**Comment by aggFTW** [comment]
When we are creating the pyspark command, we have this in [SQLQuery](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/sqlquery.py#L38):

```
        if kind == constants.SESSION_KIND_PYSPARK:
            return self._pyspark_command(sql_context_variable_name)
        elif kind == constants.SESSION_KIND_PYSPARK3:
            return self._pyspark_command(sql_context_variable_name, False)
```

which means that encode result only happens when the Livy session is running on python 2 and it doesn't happen on python 3.

When you run the pyspark (python 2) kernel, can you please check what version of python Livy is actually executing in? You can do this by issuing this code from the kernel:

```
import platform
print(platform.python_version())
```

Is Livy properly set so that it runs on python 2 for the pyspark kernel and on python 3 for the pyspark3 kernel?

**Comment by daithang1111** [comment]
Thanks. We figured out this mistake today. I was going to post and say 'thank you'.
The main reason is of the PYSPARK3_PTHON  setting from Livy configuration.

**Comment by aggFTW** [comment]
No worries. Glad you found how to fix it. Livy does need to be set up properly so that it respects running on python 2 or 3 accordingly.
