### ISSUE TITLE
Command remains in Running state

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#339]
FROM: https://groups.google.com/forum/#!topic/jupyter/jaLKe6uy91Y

---------------------------------------------------------------------------------------------------------

Hello All, 

I am trying to debug an issue in a notebook running the Pyspark kernel where the notebook will execute some cells  but then freeze after a certain point. I think that messaging is getting screwed up between Pyspark and Livy. When the last cell is executed, I will see this on the client side. 

2017-03-08 22:24:48,505 INFO    EventsHandler   InstanceId: 0e1c8fd2-047e-4337-b264-5b64ba74de5a,EventName: notebookStatementExecutionStart,Timestamp: 2017-03-08 22:24:48.504920,SessionGuid: 03d14478-6adc-4b
34-abef-b9b6fd400543,LivyKind: pyspark,SessionId: 8,StatementGuid: f1933b11-b767-4a18-b311-c48901ad8369
2017-03-08 22:24:48,788 DEBUG   Command Status of statement 8 is running.
2017-03-08 22:24:50,920 DEBUG   Command Status of statement 8 is running.

 ...and it never comes back.

On the livy end, I see 

17/03/08 17:26:26 INFO ContextLauncher: 17/03/08 17:26:26 INFO scheduler.DAGScheduler: ResultStage 17 (collect at <stdin>:5) finished in 1.521 s
17/03/08 17:26:26 INFO ContextLauncher: 17/03/08 17:26:26 INFO scheduler.DAGScheduler: Job 8 finished: collect at <stdin>:5, took 3.729078 s
17/03/08 17:26:27 DEBUG RpcDispatcher: [ClientProtocol] Registered outstanding rpc 230 (com.cloudera.livy.rsc.BaseProtocol$GetReplJobResult).
17/03/08 17:26:27 DEBUG KryoMessageCodec: Encoded message of type com.cloudera.livy.rsc.rpc.Rpc$MessageHeader (6 bytes)
17/03/08 17:26:27 DEBUG KryoMessageCodec: Encoded message of type com.cloudera.livy.rsc.BaseProtocol$GetReplJobResult (91 bytes)
17/03/08 17:26:27 DEBUG KryoMessageCodec: Decoded message of type com.cloudera.livy.rsc.rpc.Rpc$MessageHeader (6 bytes)
17/03/08 17:26:27 DEBUG KryoMessageCodec: Decoded message of type com.cloudera.livy.rsc.rpc.Rpc$NullMessage (2 bytes)
17/03/08 17:26:27 DEBUG RpcDispatcher: [ClientProtocol] Received RPC message: type=REPLY id=230 payload=com.cloudera.livy.rsc.rpc.Rpc$NullMessage
17/03/08 17:26:28 DEBUG RpcDispatcher: [ClientProtocol] Registered outstanding rpc 231 (com.cloudera.livy.rsc.BaseProtocol$GetReplJobResult).

ad infinitum

So, with my limited knowledge, it looks to me that Livy thinks it has sent a result to a finished job, but pyspark hasn't received it.
Anyone seen this before? Any thoughts?

Thanks!
--Willie

**Comment by aggFTW** [comment]
Willie, is the code you are writing that results into this always the same? Is there a way to repro?
If it works on every cell but not on a particular one, I think it might be that the code is not completing in the time you thought it would and not a sparkmagic-livy communication issue.

It would be good to understand the status of the Livy statement ID that the cell is running at that moment. If it is still in `running` state, then sparkmagic is doing the right thing and we would need to figure out why Livy is keeping the statement as `running` when you think it shouldn't be in running state. Can you please verify the status of the statement? You can do this by going to /sessions/SESSIONID/statements and looking to see if there's any statement in `running` state when the notebook hangs.

**Comment by wkupersa** [comment]
Thank you for the pointer to the livy endpoint and the assist! I realized that I was doing something dumb in my code, but I am still not sure why I am not seeing an error but instead getting this behavior. 

So the dumb thing that I was doing was calling collect() on a dataframe with ~2 million rows. I am doing this after a groupby and count operation. 

xx = sysmon_matcheddf.groupBy(col("id")).count()
xx.collect()

The thing that seems odd to me with this in mind is if I run collect on other large dataframes, I get an error back from spark. This just sits until eventually Yarn kills the session for inactivity. 

When I look at the endpoint, this is the result
        {
            "id": 8,
            "output": null,
            "state": "running"
        }
    ],

The reason that I though that everything was done was that Spark shows no pending or active jobs or stages and the livy log (grepped for job) says ...

17/03/09 14:13:08 INFO ContextLauncher: 17/03/09 14:13:08 INFO scheduler.DAGScheduler: Got job 6 (collect at <stdin>:1) with 200 output partitions
17/03/09 14:14:24 INFO ContextLauncher: 17/03/09 14:14:24 INFO scheduler.DAGScheduler: Job 6 finished: collect at <stdin>:1, took 76.534759 s

So, I was crazy to think that the collect() wouldn't blow things up, but it still seems like odd behavior to me.  Thanks again for the help!

**Comment by aggFTW** [comment]
It seems strange... you may want to file an incident with Livy regarding unclear logs: https://issues.cloudera.org/projects/LIVY/issues
