### ISSUE TITLE
Remote repositories to search for the maven coordinates

### ISSUE THREAD

**Issue by anskarl** [jupyter-incubator/sparkmagic#344]
Hi,

Is there any way to add additional remote maven repositories, in order to search for coordinates that are given in the "spark.jar.packages" ? For example, spark-submit and spark-shell have the `--repositories` parameter which does exactly that. 

This is related to question: https://github.com/jupyter-incubator/sparkmagic/issues/260#issuecomment-229400839

Thanks,

Anastasios

**Comment by aggFTW** [comment]
https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-spark-jupyter-notebook-use-external-packages

So it looks like:
```
%%configure
{ "conf": {"spark.jars.packages": "com.databricks:spark-csv_2.10:1.4.0" }}
```

You can pass to the `%%configure` magic anything that Livy supports in the `/sessions` POST body: https://github.com/cloudera/livy#post-sessions

**Comment by anskarl** [comment]
Hi, 

No this is not what I am asking, I want to define a private repository for downloading the packages. The default behavior is to download only the ones that are available through Maven central. That's why I referred the `--repositories` parameter of `spark-submit` and `spark-shell`.

**Comment by aggFTW** [comment]
You want to pass `spark.jars.ivy`. Refer to https://spark.apache.org/docs/latest/configuration.html

As I mentioned, you can pass anything that Livy supports in the `/sessions` POST body, and the `conf` key allows you to pass any Spark configuration via key, value.
