### ISSUE TITLE
Enable -o/--output for -c spark/pyspark along with sql

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [jupyter-incubator/sparkmagic#345]
Hi,

Storing output to a variable using -o option (`%%spark -c sql -o data`)is really useful. Can we enable the same for spark/pypspark context?

**Comment by aggFTW** [comment]
It's already there 😄 

Just upgrade to the latest version and issue the help command to see how to use it. You will pass `-o name_of_spark_dataframe` and will get `name_of_spark_dataframe` in the local context as a pandas dataframe.

**Comment by praveenkanamarlapudi** [comment]
Thanks for the info @aggFTW  :)
