### ISSUE TITLE
Unrecognized magics make cell run locally

### ISSUE THREAD

**Issue by danfike** [jupyter-incubator/sparkmagic#347]
It seems that any cell which begins with a nonexistent magic (e.g. `%asdf`) will cause the body of the cell to run locally. I wouldn't expect the code to run locally without `%%local`.

As a demonstration, note how the final cell here outputs the number `15` and not `10`:
![image](https://cloud.githubusercontent.com/assets/8999918/25249448/7e0c7948-25d7-11e7-980b-d62b1101b1ba.png)

## Observed with
notebook 4.4.1
sparkmagic 0.11.1
kernel PySpark

**Comment by aggFTW** [comment]
Yes, that is expected. The kernels are implemented on top of the IPython kernel, using its magics framework. Behind the covers, `In[15]` in the picture is being translated into
```
%%spark
x = 10
```

So, if the code is supposed to run on Spark, it shouldn't include any magics.
