### ISSUE TITLE
Post Binary Files and configure PYSPARK_PYTHON

### ISSUE THREAD

**Issue by quasiben** [jupyter-incubator/sparkmagic#348]
Spark's Python and R execution environments can be controlled with [environment variables](http://spark.apache.org/docs/latest/configuration.htm): `PYSPARK_PYTHON`, `SPARKR_DRIVER_R`, etc.  Additionally, we can manipulate the driver and worker execution environments if we create an [archive](http://spark.apache.org/docs/latest/running-on-yarn.html) and ship this along with a Spark job spec.  Can sparkmagic set the environment variables and upload an archive before a spark context is create?

@martindurant is also asking a similar question on Livy's JIRA: https://issues.cloudera.org/browse/LIVY-347

**Comment by aggFTW** [comment]
Similar to #344, it seems like you want to pass some spark configuration `spark.executorEnv.[EnvironmentVariableName]` to conf via the `%%configure` magic. Please refer to https://spark.apache.org/docs/latest/configuration.html#runtime-environment and https://github.com/cloudera/livy#post-sessions

**Comment by martindurant** [comment]
@aggFTW , please let me clarify. The jars, files, archives parameters accept strings that will be uploaded to the cluster by livy from the machine on which livy is running. 

However, we have sparkmagic running on a different machine and wish to upload files for distribution to the cluster. Can this be done?

**Comment by quasiben** [comment]
Any chance we could reopen this issue and continue discussing ?

**Comment by aggFTW** [comment]
No, you cannot upload files via sparkmagic. You can specify environment variables for the Livy session you open via sparkmagic, but that's about it.

What's the use case?

**Comment by martindurant** [comment]
The use case if of providing a user-specified environment for spark to execute in, shipped at run-time, without having to change the operation of the (yarn) cluster itself. This way, you can get isolated, contained spark workers with all packages installed that the user wants, without involving the cluster management team. Such a thing is possible using spark-submit from an edge-node.

**Comment by aggFTW** [comment]
Got it. We cannot use sparkmagic to upload files now.

You would specify the `jars` option in Livy's POST request. If you wanted to specify a local path to the jars, that path would have to be local to the Livy server.

In the end, it sounds like you need to upload the files out of band and then specify the location to those jars in HDFS from sparkmagic. Sorry there isn't a better story yet.

**Comment by quasiben** [comment]
Ok, this can probably closed. Thanks @aggFTW for the discussion

**Comment by aggFTW** [comment]
No worries, thank you!

**Comment by JunweiSUN** [comment]
> No, you cannot upload files via sparkmagic. You can specify environment variables for the Livy session you open via sparkmagic, but that's about it.
> 
> What's the use case?

Hi @aggFTW , sorry to bother, but could you tell me how can I add extra jars to the livy session created by sparkmagic. Should I edit the configure json file in livy or just specific the path of the jars in the opened notebook with some code supported by sparkmagic like
```
%addjar hdfs:///some-extra.jar
```
