### ISSUE TITLE
Limit on number of rows using %%spark -o or %%sql -o ?

### ISSUE THREAD

**Issue by edoardovivo** [jupyter-incubator/sparkmagic#349]
Hello, 
I am experiencing an issue in transferring a remote spark dataframe to a local pandas dataframe. 
The spark dataframe has got 2828 rows and 3 columns. However, when I use the following command
```
%%spark -o df_local
df_local = df_remote
```
Then the df_local pandas dataframe has got 2500 rows. The same thing happens if I execute
```
%%sql -o df_local
SELECT * FROM remote
```
where "remote" is a registered table. 

Is there a limit on the number of rows that can be transferred? Am I doing something wrong?

Reproducible code:
```
rdd = sc.parallelize([(1,1,1,1,1,1)]*2499)
df_test = spark.createDataFrame(rdd, ["id", "score1", "score2", "score3", "score4", "score5"])
--
%%spark -o df_test_local
df_test_local = df_test
--
%%local
df_test_local.shape
--
rdd = sc.parallelize([(1,1,1,1,1,1)]*2501)
df_test = spark.createDataFrame(rdd, ["id", "score1", "score2", "score3", "score4", "score5"])
--
%%spark -o df_test_local
df_test_local = df_test
--
%%local
df_test_local.shape
```
The last comand yields (2500, 6).

Any help is much appreciated. 
Thank you, 
Edoardo

**Comment by aggFTW** [comment]
Please execute `%%help` in the kernel to look at the parameters that you can use to specify max number of rows. Default is 2500.

**Comment by edoardovivo** [comment]
Thank you very much, and my apologies for the dumb question.
However, I do believe that issuing a warning in case the number of lines of the original dataframe exceeds 2500 (in case the -n option is not specified) would be really helpful, especially to newbies like me.
I don't know if it's feasible, but, again, just a suggestion.
Thank you and apologies again.

**Comment by aggFTW** [comment]
No worries :) Happy to help.

The reason we don't emit a warning is that in order to know that 2500 was not enough, we would need to issue a `count()` on the dataframe, and that might end up taking a long time to execute, depending on the dataframe. So we don't do it and think that an "always on" warning would be annoying. Thanks for the suggestion!

**Comment by Nithanaroy** [comment]
Big fan of this library! Thank you for creating this.

Like @edoardovivo, I spent a lot of time trying to understand why only 2500 rows were returned as well. Would be nice to show a message at least, if not warning just like Spark does for `.show()`. If not, please list the default values in `%%help` or somewhere
