### ISSUE TITLE
Problems with yarn-cluster mode

### ISSUE THREAD

**Issue by quasiben** [jupyter-incubator/sparkmagic#352]
## Setup
- centos 7
- cdh 5.5.X
- livy 3.0

## Issue
When running sparkmagic with livy configured to `yarn-client` or `yarn-cluster`:

```
# What spark master Livy sessions should use.
livy.spark.master = yarn-client
```

Things generally work.  However, as part of my interactive session I'd like to use archives and munge environment variables like the following:

```
{"conf": {"spark.yarn.appMasterEnv.PYSPARK_PYTHON": "./ANACONDA/env/bin/python", 
         "spark.yarn.executorEnv.PYSPARK_PYTHON": "./ANACONDA/env/bin/python"},
 "executorMemory": "2048M", "executorCores": 1,
 "archives": ["hdfs:///user/centos/environment_27.zip#ANACONDA"]}
```

When using something like the above sparkmagic always timesout.  On the livy side I see things like the following:

> 17/05/03 15:35:33 DEBUG AbstractConnection: fillInterested HttpConnection@496bb752[FILLING,SelectChannelEndPoint@32206cb9{/10.0.0.221:50869<->8998,Open,in,OSHUT,-,-,0/30000,HttpConnection}{io=0,kio=0,kro=1}][p=HttpParser{s=CLOSED,0 of 0},
g=HttpGenerator{s=START},c=HttpChannelOverHttp@5c8fd76{r=1,c=false,a=IDLE,uri=}]
17/05/03 15:35:33 DEBUG AbstractConnection: FILLING-->FILLING_FILL_INTERESTED HttpConnection@496bb752[FILLING_FILL_INTERESTED,SelectChannelEndPoint@32206cb9{/10.0.0.221:50869<->8998,Open,in,OSHUT,-,-,0/30000,HttpConnection}{io=0,kio=0,kro
=1}][p=HttpParser{s=CLOSED,0 of 0},g=HttpGenerator{s=START},c=HttpChannelOverHttp@5c8fd76{r=1,c=false,a=IDLE,uri=}]
17/05/03 15:35:33 DEBUG AbstractConnection: FILLING_FILL_INTERESTED-->FILL_INTERESTED HttpConnection@496bb752[FILL_INTERESTED,SelectChannelEndPoint@32206cb9{/10.0.0.221:50869<->8998,Open,in,OSHUT,-,-,1/30000,HttpConnection}{io=0,kio=0,kro
=1}][p=HttpParser{s=CLOSED,0 of 0},g=HttpGenerator{s=START},c=HttpChannelOverHttp@5c8fd76{r=1,c=false,a=IDLE,uri=}]
17/05/03 15:35:33 DEBUG SelectChannelEndPoint: Local interests updating 0 -> 1 for SelectChannelEndPoint@32206cb9{/10.0.0.221:50869<->8998,Open,in,OSHUT,R,-,0/30000,HttpConnection}{io=1,kio=0,kro=1}
17/05/03 15:35:33 DEBUG SelectorManager: Queued change org.eclipse.jetty.io.SelectChannelEndPoint$1@789f4f62
17/05/03 15:35:33 DEBUG SelectorManager: Selector loop woken up from select, 0/1 selected
17/05/03 15:35:33 DEBUG SelectorManager: Running change org.eclipse.jetty.io.SelectChannelEndPoint$1@789f4f62
17/05/03 15:35:33 DEBUG SelectChannelEndPoint: Key interests updated 0 -> 1 on SelectChannelEndPoint@32206cb9{/10.0.0.221:50869<->8998,Open,in,OSHUT,R,-,0/30000,HttpConnection}{io=1,kio=1,kro=1}
17/05/03 15:35:33 DEBUG SelectorManager: Selector loop waiting on select

And after a few seconds `50869` is increased to `50870` until the timeout.  I've increased the `livy_session_startup_timeout_seconds`  but this is probably not what I want.  cc @martindurant

**Comment by aggFTW** [comment]
Please open a Livy JIRA for this, since this is not a sparkmagic issue. The way to think about this is to see if any other client, besides sparkmagic, would also run into this issue or not. It sound like it would.

Depending on whether the Livy session ever reaches a running status or not, the question to ask there is why an interactive session is failing to start up when passing in those parameters. I'm guessing they would like to know if you can use those same parameters with spark-submit, and how that works.
