### ISSUE TITLE
Installing SparkMagic on PySpark docker image

### ISSUE THREAD

**Issue by buinauskasevaldas** [jupyter-incubator/sparkmagic#356]
I'm having some trouble installing/accessing SparkMagic on following docker image:

https://github.com/jupyter/docker-stacks/tree/master/pyspark-notebook

I do the following:
 1. Create a new Python 3 notebook
 2. Type the following:

```
 !pip install sparkmagic && \
    jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

And then I try to run `%%help` magic, however it's not recognized. Am I missing something?

**Comment by aggFTW** [comment]
You need to do modify the image via the docker file, and not from within the docker container.
You need to install sparkmagic before the jupyter server gets started. You need to also have installed livy, and start it as part of the docker start script (unless you already have livy running in a remote spark cluster) and you are just going to configure the sparkmagic config.json file to point to that remote livy server.

**Comment by buinauskasevaldas** [comment]
That's very clear. Many thanks!
