### ISSUE TITLE
Logger config overwrite

### ISSUE THREAD

**Issue by wikusbrink** [jupyter-incubator/sparkmagic#360]
Our project imports the Spark Magic project to interact with Livy. We found that our logger stopped working when we start using the package. It looks like the problem comes in with the following line 

```logging.config.dictConfig(logging_config)```

in `hdijupyterutils.log`, that overwrites our logger config.

**Comment by aggFTW** [comment]
You can configure which logging to use via the config file:
https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/example_config.json#L14
