### ISSUE TITLE
Can Not Access numpy from sparkmagic pyspark kernel

### ISSUE THREAD

**Issue by vidit-bhatia** [jupyter-incubator/sparkmagic#363]
I have setup a mesos server and have livy installed on the same server Have configured spark to run on mesos. 

My spark related configuration is all working as I get a spark session created and I can do operation on it.
When I try to import numpy. I get the following error.
`No module named numpy
Traceback (most recent call last):
ImportError: No module named numpy`

I have installed numpy in all the box. In fact when I use python 3 notebook I can access numpy but not from pyspark. Am I doing something wrong.

All numpy , SparkMagic and jupyter were install through pip3.6 on Centos

**Comment by aggFTW** [comment]
What python installation is livy using? If you use that python installation, from that node, can you import numpy?

**Comment by vidit-bhatia** [comment]
Thanks you hit the nail on the head.

I installed numpy on the mesos master node where livy is running and now I can import numpy also I tried doing this 
`%%Local
import numpy as np`

and it worked.

This makes sense as the livy server is trying to run code on master node.

Closing the issue now

**Comment by aggFTW** [comment]
Cool, I'm happy you worked it out.
