### ISSUE TITLE
No connection adapters were found

### ISSUE THREAD

**Issue by rsuhada** [jupyter-incubator/sparkmagic#372]
I'm trying to run pyspark code on a remote cluster. The kernel is always busy and in logs I find:

    ERROR   ReliableHttpClient      Request to 'XXX.XX.XX.XX:8998/sessions' failed with 'No connection adapters were found for 'XXX.XX.XX.XX:8998/sessions''

livy server is running and I can connect to it from my local machine (e.g. ping it with curl). When I log in to remote I can run pyspark without issues.

I took the example config and filled out my credentials:
  "kernel_python_credentials" : {
    "username": "XXXXX",
    "password": "XXXXX",
    "url": "XXX.XX.XX.XX:8998",
    "auth": "Kerberos"
  },

My info:
1) Local:
Python 2.7.12, sparkmagic, Version: 0.11.4 on Ubuntu 16.04.2 LTS

2) Remote:
Python 2.6.6, Spark version 1.6.2

Thank you!

**Comment by aggFTW** [comment]
https://stackoverflow.com/a/15115345/1663781

Thanks!

**Comment by rsuhada** [comment]
Very cool! Works. Thank you!
