### ISSUE TITLE
LivySession unexpectedly reached final status

### ISSUE THREAD

**Issue by akanksha2507** [jupyter-incubator/sparkmagic#381]
Hello I am getting the below error again and again. I just started the livy server and installed sparkmagics. In my notebook it shows below error.

<img width="1049" alt="screen shot 2017-07-05 at 1 08 14 pm" src="https://user-images.githubusercontent.com/19259459/27882818-171598a4-6183-11e7-95c9-a5d15881fb12.png">

<img width="1144" alt="screen shot 2017-07-04 at 2 17 10 pm" src="https://user-images.githubusercontent.com/19259459/27882783-ec3839e8-6182-11e7-9b42-71128cb6ec07.png">

I cannot see much in logs too.
[logs.txt](https://github.com/jupyter-incubator/sparkmagic/files/1125907/logs.txt)

Thanks so much for your help

**Comment by aggFTW** [comment]
Livy is failing to create the session. Look at the livy logs (not sparkmagic logs) to see why.

**Comment by aggFTW** [comment]
Closing for now, as this is not a sparkmagic issue.
