### ISSUE TITLE
Sessions in Manage Endpoints and Manage sessions not in sync

### ISSUE THREAD

**Issue by pranayhasan** [jupyter-incubator/sparkmagic#386]
The sessions in manage endpoints tab are not in synch with the sessions in manage sessions tab in widget UI as show below. 

The session 6 has been deleted from manage endpoints as shown below, but the UI continues to display the session in the endpoint list.

<img width="898" alt="screen shot 2017-07-24 at 11 42 56 am" src="https://user-images.githubusercontent.com/5507845/28510327-6ecb6704-7065-11e7-807e-853d763e335a.png">

Even the manage sessions UI displays the deleted session as below:
<img width="901" alt="screen shot 2017-07-24 at 11 42 38 am" src="https://user-images.githubusercontent.com/5507845/28510324-68a7c9c6-7065-11e7-88e1-39cbf5c46f99.png">

This is primarily due to the methods that are used in spark controller.

### Method called when deleting session from manage endpoint widget
_Class: Spark Controller_
`delete_session_by_id(endpoint, session_id) -calls-> creates a new LivySession object, say ls with LivyReliableHTTPClient and does ls.delete()`
This method doesn't go through the session manager route and hence the sessions in session manager continue to exist even after being deleted. The status shown in manage sessions tab

### Method called when deleting from manage sessions widget
_Class: Spark Controller_
`delete_session_by_name(name) -calls-> session_manager.delete_client(name)`
This method cleanly deletes the session by removing session from the sessions managed by session manager.

So, to make the experience consistent the method **delete_session_by_id** needs to be updated to go through session manager route.

**Comment by aggFTW** [comment]
I will look into how we can improve this later in this week. I'm currently traveling.
