### ISSUE TITLE
Notebook Kernel getting into infinite loop when executing %info magic

### ISSUE THREAD

**Issue by pranayhasan** [jupyter-incubator/sparkmagic#396]
When executing %info magic, the result is returned but notebook in kernel is getting stuck in the busy state forever.

<img width="1143" alt="screen shot 2017-08-08 at 2 41 16 pm" src="https://user-images.githubusercontent.com/5507845/29064775-b6f05862-7c47-11e7-8267-56e08e2df893.png">

**Comment by aggFTW** [comment]
What does "the result is returned" mean?

If you do the same http request info is doing against your livy server, is the request coming back?
Have you looked at the sparkmagic logs for any errors?

**Comment by pranayhasan** [comment]
The result of the %info magic is returned but the kernel gets into "busy" mode endlessly.

> 2017-08-09 10:57:11,403	ERROR	ReliableHttpClient	Request to 'http://localhost:8998/sessions' failed with 'HTTPConnectionPool(host='localhost', port=8998): Max retries exceeded with url: /sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111226d90>: Failed to establish a new connection: [Errno 61] Connection refused',))'
> 2017-08-09 10:57:16,409	ERROR	ReliableHttpClient	Request to 'http://localhost:8998/sessions' failed with 'HTTPConnectionPool(host='localhost', port=8998): Max retries exceeded with url: /sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111261390>: Failed to establish a new connection: [Errno 61] Connection refused',))'

The above messages are being emitted endlessly. localhost is being used instead of the added endpoint URL here.

**Comment by aggFTW** [comment]
And what is the right endpoint? Localhost?
________________________________

**Comment by aggFTW** [comment]
Why are you managing session via the `spark` kernel? Please look into the sample notebooks for how to configure the standalone kernels via the `config.json` file. You are not supposed to create sessions manually. The kernel manages session creation for you.

You need to add the right endpoints into your config file.
