### ISSUE TITLE
Update the environment variables of the SparkSubmit process (yarn spark client spawned by Livy Server)

### ISSUE THREAD

**Issue by jimdowling** [jupyter-incubator/sparkmagic#397]
I need to update the environment variables of the SparkSubmit process (i need to add PYSPARK_PYTHON to support using a conda environment). 
However, i can't figure out how to do this (apart from updating the global $SPARK_HOME/conf/spark-env.sh).  Can I do this through configuration or does it need a PR (which I would be willing to contribute)?

**Comment by aggFTW** [comment]
You can specify environment variables via `conf` for the livy session (https://github.com/cloudera/livy#post-sessions) as documented in the spark documentation (`spark.executorEnv.[EnvironmentVariableName]`) here https://spark.apache.org/docs/latest/configuration.html.

**Comment by jimdowling** [comment]
Thanks @aggFTW , however Livy will start a Spark client that launches a local python program - if you start a livy session for PySpark and then type 'jps' on the Livy server as the livy user, you will see a SparkSubmit process has been created that in turn spawns a local python interpreter process. If that SparkSubmit process (which is the yarn client that launches PySpark jobs in yarn-cluster mode) does not have the PYSPARK_PYTHON environment variable set, then it will use the default /usr/bin/python interpreter. I want it to use an anaconda python binary in another folder (to use the libraries installed in my anaconda environment).  
The spark.executorEnv.[EnvironmentVariableName], spark.driverEnv.[EnvironmentVariableName], and spark.yarn.AppMasterEnv.[EnvironmentVariableName] are for processes in the yarn cluster. I want to set env variables for the Spark Client launched by Livy (and not do it in the global spark-env.sh file - but do it on a per-command basis).

**Comment by jimdowling** [comment]
Ok, i resolved this. The problem for me was that in the conf for the livy session, I did not set spark.submit.deployMode. It defaulted to 'local', and this causes the sparkDriver to be launched locally at the Livy server. The spark.driverEnv.[Env Props] weren't respected by Livy. 
However, when I set spark.submit.deployMode='cluster', the spark.yarn.appMasterEnv.PYSPARK_PYTHON environment variable was set correctly. You can close (but this info might be useful for others who want to use Anaconda with Pyspark).

**Comment by aggFTW** [comment]
Glad you found the issue :)

**Comment by pruthvi247** [comment]
> Ok, i resolved this. The problem for me was that in the conf for the livy session, I did not set spark.submit.deployMode. It defaulted to 'local', and this causes the sparkDriver to be launched locally at the Livy server. The spark.driverEnv.[Env Props] weren't respected by Livy.
> However, when I set spark.submit.deployMode='cluster', the spark.yarn.appMasterEnv.PYSPARK_PYTHON environment variable was set correctly. You can close (but this info might be useful for others who want to use Anaconda with Pyspark).

should we set this property while creating livy session like below

data = {'kind': 'pyspark','driverMemory':'2G','driverCores':2,'numExecutors': 1,
            'executorMemory': '1G','executorCores':1,'conf':{'spark.pyspark.virtualenv.enabled':'true',
            'spark.pyspark.virtualenv.type':'conda',
            'spark.submit.deployMode':'cluster'
            'spark.pyspark.virtualenv.path':'/home/ds_cpu_adm/.conda/envs/conda_test_env/bin/python'}}
