### ISSUE TITLE
%load_ext sparkmagic.magics doesn't work

### ISSUE THREAD

**Issue by abhijitjaiswal** [jupyter-incubator/sparkmagic#398]
I installed Jupyter and sparkmagic, created a config.json under ~/.sparkmagic folder:
config.json:
**{
  "kernel_python_credentials" : {
    "username": "",
    "password": "",
    "url": "http://<public_ip_of_spark_cluster>:8998"
},

  "kernel_scala_credentials" : {
    "username": "",
    "password": "",
    "url": "http://<public_ip_of_spark_cluster>:8998"
},**

But when I execute "%load_ext sparkmagic.magics" on "pyspark" notebook the following error is given:

BadUserConfigurationException             Traceback (most recent call last)
<ipython-input-1-2b579b518c56> in <module>()
----> 1 get_ipython().magic(u'load_ext sparkmagic.magics')

/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2161         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2162         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2163         return self.run_line_magic(magic_name, magic_arg_s)
   2164 
   2165     #-------------------------------------------------------------------------

/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2082                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2083             with self.builtin_trap:
-> 2084                 result = fn(*args,**kwargs)
   2085             return result
   2086 

<decorator-gen-65> in load_ext(self, module_str)

/usr/local/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/usr/local/lib/python2.7/site-packages/IPython/core/magics/extension.pyc in load_ext(self, module_str)
     64         if not module_str:
     65             raise UsageError('Missing module name.')
---> 66         res = self.shell.extension_manager.load_extension(module_str)
     67 
     68         if res == 'already loaded':

/usr/local/lib/python2.7/site-packages/IPython/core/extensions.pyc in load_extension(self, module_str)
     84                     __import__(module_str)
     85             mod = sys.modules[module_str]
---> 86             if self._call_load_ipython_extension(mod):
     87                 self.loaded.add(module_str)
     88             else:

/usr/local/lib/python2.7/site-packages/IPython/core/extensions.pyc in _call_load_ipython_extension(self, mod)
    131     def _call_load_ipython_extension(self, mod):
    132         if hasattr(mod, 'load_ipython_extension'):
--> 133             mod.load_ipython_extension(self.shell)
    134             return True
    135 

/usr/local/lib/python2.7/site-packages/sparkmagic/magics/remotesparkmagics.pyc in load_ipython_extension(ip)
    192 
    193 def load_ipython_extension(ip):
--> 194     ip.register_magics(RemoteSparkMagics)

/usr/local/lib/python2.7/site-packages/IPython/core/magic.pyc in register(self, *magic_objects)
    389             if isinstance(m, type):
    390                 # If we're given an uninstantiated class
--> 391                 m = m(shell=self.shell)
    392 
    393             # Now that we have an instance, we can register it and update the

/usr/local/lib/python2.7/site-packages/sparkmagic/magics/remotesparkmagics.pyc in __init__(self, shell, data, widget)
     30         self.endpoints = {}
     31         if widget is None:
---> 32             widget = MagicsControllerWidget(self.spark_controller, IpyWidgetFactory(), self.ipython_display)
     33         self.manage_widget = widget
     34 

/usr/local/lib/python2.7/site-packages/sparkmagic/controllerwidget/magicscontrollerwidget.pyc in __init__(self, spark_controller, ipywidget_factory, ipython_display, endpoints)
     16 
     17         if endpoints is None:
---> 18             endpoints = {endpoint.url: endpoint for endpoint in self._get_default_endpoints()}
     19         self.endpoints = endpoints
     20 

/usr/local/lib/python2.7/site-packages/sparkmagic/controllerwidget/magicscontrollerwidget.pyc in _get_default_endpoints()
     36                     auth=endpoint_config.get("auth", None),
     37                     url=endpoint_config["url"],
---> 38                     implicitly_added=True))
     39 
     40         return default_endpoints

/usr/local/lib/python2.7/site-packages/sparkmagic/livyclientlib/endpoint.pyc in __init__(self, url, auth, username, password, implicitly_added)
      8             raise BadUserDataException(u"URL must not be empty")
      9         if auth not in AUTHS_SUPPORTED:
---> 10             raise BadUserConfigurationException(u"Auth '{}' not supported".format(auth))
     11 
     12         self.url = url.rstrip(u"/")

BadUserConfigurationException: Auth 'None' not supported

Can someone point me to solution.

**Comment by aggFTW** [comment]
This was fixed in 0.12.3: https://github.com/jupyter-incubator/sparkmagic/pull/389/files#diff-a6fed1227c6e8bc5f95aec7373995c73R38

Can you please update your installation to use that version?

**Comment by abhijitjaiswal** [comment]
Thanks @aggFTW that worked 👍
