### ISSUE TITLE
Improve initial documentation

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#4]

**Comment by alope107** [comment]
We should improve the example notebook as part of the documentation.

**Comment by aggFTW** [comment]
Yes... in regards to the notebook and instructions on how to use the magics, I was waiting for you to refactor the API and then do it. Do you think that's fair?

**Comment by aggFTW** [comment]
We need a set of notebooks:
* Spark magic usage
* Pyspark kernel simple usage
* Scala kernel simple usage
