### ISSUE TITLE
Adding default CSRF header as a good security practice .

### ISSUE THREAD

**Issue by JeffRodriguez** [jupyter-incubator/sparkmagic#401]
It is no harm to set X-Requested-By when csrf protection is disabled. This will help user experience so when livy CsrfFilter check for "X-Requested-By" header it doesn't return a ""Missing Required Header for CSRF protection."
Check the usage of CSRF headers at owasp.
The main idea is to check the presence of a custom header (agreed-upon between the server and a client – e.g. X-CSRF or X-Requested-By) in all state-changing requests coming from the client.

**Comment by JeffRodriguez** [comment]
I have the code to contribute, can I get contributor access, or this to issue be assigned to me.
Thanks.

**Comment by aggFTW** [comment]
You can submit the PR without contributor access. Submit and we'll help you get it in.

Thanks for reporting and contributing!

**Comment by aggFTW** [comment]
Was the PR closed because headers are configurable?

**Comment by JeffRodriguez** [comment]
I am re-opening a new PR. The issue is still valid since the idea is to default the CSRF headers.

I close the PR because I failed a test on Python 3.

**Comment by JeffRodriguez** [comment]
Thanks for you comments. :-) I am still getting around with PR. I usually submit patches for my other projects contributions.
Regards,
       Jeff

**Comment by JeffRodriguez** [comment]
Just send PR. 
Regards,
         Jeffrey Rodriguez

**Comment by aggFTW** [comment]
Closing, as explained at https://github.com/jupyter-incubator/sparkmagic/pull/403
