### ISSUE TITLE
Error on docker-compose build 

### ISSUE THREAD

**Issue by sangramga** [jupyter-incubator/sparkmagic#405]
I just cloned the git repository of sparkmagic in order to get docker-file
I have docker and docker-compose installed without any errors.
**I am getting an error when I build the docker-compose file**
Here are the screenshots
![docker-compose-build_sparkmagic](https://user-images.githubusercontent.com/9406431/29907496-48c42374-8e39-11e7-9192-47303c977121.png)

**Comment by aggFTW** [comment]
This issue should be unrelated to sparkmagic. Some related threads I found:

https://stackoverflow.com/questions/44080220/docker-failed-to-fetch-http-deb-debian-org-debian-dists-jessie-inrelease
https://stackoverflow.com/questions/24991136/docker-build-could-not-resolve-archive-ubuntu-com-apt-get-fails-to-install-a?noredirect=1&lq=1
