### ISSUE TITLE
Let different jupyter kernel use different sparkmagic config.json file

### ISSUE THREAD

**Issue by yunzhums** [jupyter-incubator/sparkmagic#406]
Hi,

I am looking for a solution to let different jupyter kernel use different sparkmagic config.json file, but I cannot find any documentations about this use case. Then I dive deep into sparkmagic's code base and find an environment variable SPARKMAGIC_CONF_FILE: https://github.com/jupyter-incubator/sparkmagic/blob/622048d79c556ad40a785449a82466ec93d7b05a/sparkmagic/sparkmagic/utils/constants.py

By adding this environment variable in our jupyter kernel's kernel.json, I can solve my problem.

Just curious, any suggestions about this use case? Since no documentation about using the environment variable: SPARKMAGIC_CONF_FILE.

Thanks,
Yunshan

**Comment by aggFTW** [comment]
It's not possible to use different config files at the moment. What is the use case? Why do you need different configs?

**Comment by yunzhums** [comment]
On Azure HDInsight cluster, it has pyspark and pyspark3 jupyter kernel, and both of them are using sparkmagic. For some reasons, we want to add additional spark configs only for the pyspark3 kernel while we don't want to affect the pyspark kernel. Directly changing .sparkmagic/config.json will affect both, so we are looking for any ways to use different config files. 
Then I find this environment variable in code base: SPARKMAGIC_CONF_FILE

**Comment by aggFTW** [comment]
Yes, so this env variable changes things for all kernels, so that's not your answer. May I ask what configs are these? At the moment, there's no way to target just one kernel. Maybe I can try to think of a mitigation if you explain your needs in greater detail.

**Comment by yunzhums** [comment]
Basically we want to set these config: 
spark.yarn.appMasterEnv.PYSPARK3_PYTHON
spark.pyspark.python

The goal is to point the pyspark3 python interpreter to our own interpreter, while we don't to affect the pyspark kernel's python interpreter.

**Comment by yunzhums** [comment]
My current solution is to create a new config file named config2.json also in .sparkmagic/ folder. And add this env slot to pyspark3 kernel's kenel.json file:
 "env": {
   "SPARKMAGIC_CONF_FILE": "config2.json"
 }

**Comment by aggFTW** [comment]
The python interpreter to be used is not controlled by sparkmagic, but by Livy. You can configure which interpreter livy uses for python 3 sessions by following the instructions at https://github.com/cloudera/livy#pyspark3

You don't need to modify anything on jupyter/sparkmagic side.
