### ISSUE TITLE
Question: How to use Jupyter + SparkR and custom R install

### ISSUE THREAD

**Issue by rrussell39** [jupyter-incubator/sparkmagic#407]
I am using a Dockerized image and Jupyter notebook along with SparkR kernel. When I create a SparkR notebook, it uses an install of Microsoft R (3.3.2) instead of vanilla CRAN R install (3.2.3).

The Docker image I'm using installs some custom R libraries and Python pacakages but I don't explicitly install Microsoft R. Regardless of whether or not I can remove Microsoft R or have it side-by-side, how I can get my SparkR kernel to use a custom installation of R?

https://stackoverflow.com/questions/46286021/how-to-use-jupyter-sparkr-and-custom-r-install

**Comment by aggFTW** [comment]
Sparkmagic just creates an R session in Livy. Livy uses its own configs to find the right R installation. Please post this question to the Livy github page, as I'm afraid I don't know how to help here.

**Comment by rrussell39** [comment]
Thanks @aggFTW .  Just now seeing your response.
