### ISSUE TITLE
Cannot add my endpoint in sparkmagic under docker-compose in Win 10 (a newbie question)

### ISSUE THREAD

**Issue by DShevelev** [jupyter-incubator/sparkmagic#414]
I have recently downloaded the sparkmagic project (pip show sparkmagic gives me Version: 0.12.4) and running it with docker-compose under Windows 10.
I cannot make it connect on the Python 3 kernel to a Livy server my team uses for development related to Spark and Livy stuff.
The %manage_spark cell output says the endpoint was added but then shows a HttpClientException. From the stack I see it looks for me like some internal refresh fails to renew the list of the end-points on another tab. The new endpoint is not visible after that in the "Endpoint" list on the "Create session" tab.
It is not like entire "manager_spark" UI does not work. I am able to add a session to the preinstalled endpoint. So that I assume I am on the right kernel.
The screenshots and the entire cell output is attached.
Should the docker image be able to connect to real world Livy server beside the included one? Is something wrong with my server? Can it have anything to do with the Docker under Windows? Some port blocking maybe or something like that?
Could you please advise me on the matter? I am a bit puzzled as for what to do about it.
[Cell output.txt](https://github.com/jupyter-incubator/sparkmagic/files/1402525/Cell.output.txt)
![httpclientexception on refreshing end-points top](https://user-images.githubusercontent.com/32962992/31830150-06fa04de-b5c8-11e7-9fab-a0a54eddea8c.png)
![httpclientexception on refreshing end-points bottom](https://user-images.githubusercontent.com/32962992/31830162-0ca7768c-b5c8-11e7-89a2-f7cea8f653b8.png)

**Comment by aggFTW** [comment]
I suspect that the endpoint/credentials are not valid, because it's failing to make an http call to it. Should it be https perhaps? Can you hit your endpoint /sessions on a browser? Does it work?

**Comment by DShevelev** [comment]
Checked it now. Yes, it works. And it works via http. 
http://********/sessions
produces {"from":0,"total":0,"sessions":[]}

**Comment by aggFTW** [comment]
What if you something like this from Jupyter:

```
wget http://********/sessions
```

If that fails in Jupyter, but works on the browser, it might be a networking config for docker.

**Comment by DShevelev** [comment]
Yes, you are right. Looks to be just some kind of a DNS issue. The server name is not recognized in the notebook while the corresponding IP address works. As I see now I am not the first one facing DNS issues in Docker under Windows. My bad. Should have guessed earlier.
It is time to close the ticket.
Thanks a lot for a fantastic response time! Seeing developers being that responsive is one of the main reasons usually to stick to the software they create. :)
P.S. Just two points as for the sparkmagic UX. It is up to you to decide whether they are worth of creating corresponding issues.
First of all it would be great maybe to get in the UI more detailed information on errors. I am used to showing my users (at the very least) the title of the exact operation resulted in the error and any non-confidential details like the exact address that failed in that case. The more details are at hand the faster the issue can be dealt with by an inexperienced user or even by an experienced one if the issue more complicated than mine.
In my case it maybe would have been obvious for a user who understands how it works. He would have realized right away what address the error is related to. But it was not that obvious for an absolute newcomer like me. Had I seen the exact address in the error message I would have come to the same conclusion sooner I guess. When I saw just the "Error sending http request and maximum retry encountered" without operation named and the address specified I did not understand where the package tried to go to: whether it was some internal for the image resource or the endpoint I was trying to add.
And the second point. The %manage_spark UI looks for me being messed up in my Chrome browser. I would say it is nowhere near enterprise look expectations. Do not know of course whether you can do something about it or not.
![manage endpoints](https://user-images.githubusercontent.com/32962992/31849403-439456ba-b64a-11e7-9772-20bb3edeb24c.png)
![manage sessions](https://user-images.githubusercontent.com/32962992/31849404-43b338aa-b64a-11e7-935e-a191e1d6cbe1.png)

**Comment by aggFTW** [comment]
Hey, thanks so much for taking the time to leave detailed feedback. This allows us to create a better experience for all 👍 

As for better error information, let me look into it!

As for the UI issues, I'm unable to repro... could you let me know what system you have? Please list browser version, OS, ipywidgets/notebook versions.

**Comment by DShevelev** [comment]
Hello. I am back to Jupyter stuff. Here is my environment.

**Windows 10 Pro**
	Version: 1607
	OS Build: 14393.693

The messed UI looks the same in both of my primary browsers. It looks like row breaks are just ignored throughout the %manage_spark UI.

**Google Chrome** 
	Version: 62.0.3202.62 (Official Build) (64-bit)
**Firefox**
	Version: 56.0 (32-bit)

![manage_spark in firefox](https://user-images.githubusercontent.com/32962992/31988595-4cf53108-b978-11e7-9be7-1299d5224f74.png)

pip show **sparkmagic**:
	Version: 0.12.4

About **Jupyter Notebook**
	The version of the notebook server is 4.4.1 and is running on:
	Python 3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 22:59:30) 
	[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
	Current Kernel Information:
	Python 3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 22:59:30) 

Here is the "**Download Widget State**" output. Correct me if that is not what would you like to see.
[widget_state.txt](https://github.com/jupyter-incubator/sparkmagic/files/1413834/widget_state.txt)
