### ISSUE TITLE
Release timeline for latest Jupyter/Notebook version support

### ISSUE THREAD

**Issue by jasonslepicka** [jupyter-incubator/sparkmagic#417]
My apologies if this is not the appropriate avenue for this request, but I was curious if there was a timeline for the next production release to pypi that would include #408 and the latest Jupyter Notebook version support.   Please let me know when it's convenient.  Thanks!

**Comment by aggFTW** [comment]
Done :)

**Comment by jasonslepicka** [comment]
Thanks!
