### ISSUE TITLE
%manage_spark for scala only

### ISSUE THREAD

**Issue by mrunmayeejog** [jupyter-incubator/sparkmagic#423]
I have followed steps from https://github.com/jupyter-incubator/sparkmagic/ for installing scala kernel. Here I have only installed scala kernel but when I use %manage_spark I see language option for scala and python. For scala I am able to create session however when I select python I get following:

Starting Spark application

---------------------------------------------------------------------------
LivyClientTimeoutException                Traceback (most recent call last)
/opt/pnda/jupyter/lib/python3.4/site-packages/sparkmagic/livyclientlib/livysession.py in start(self)
    129             try:
--> 130                 self.wait_for_idle(conf.livy_session_startup_timeout_seconds())
    131             except LivyClientTimeoutException:

/opt/pnda/jupyter/lib/python3.4/site-packages/sparkmagic/livyclientlib/livysession.py in wait_for_idle(self, seconds_to_wait)
    245                 self.logger.error(error)
--> 246                 raise LivyClientTimeoutException(error)
    247 

LivyClientTimeoutException: Session 4 did not reach idle status in time. Current status is starting.

During handling of the above exception, another exception occurred:

LivyClientTimeoutException                Traceback (most recent call last)
/opt/pnda/jupyter/lib/python3.4/site-packages/hdijupyterutils/ipywidgetfactory.py in submit_clicked(self, button)
     63 
     64     def submit_clicked(self, button):
---> 65         self.parent_widget.run()

/opt/pnda/jupyter/lib/python3.4/site-packages/sparkmagic/controllerwidget/createsessionwidget.py in run(self)
     56 
     57         try:
---> 58             self.spark_controller.add_session(alias, endpoint, skip, properties)
     59         except ValueError as e:
     60             self.ipython_display.send_error("""Could not add session with

/opt/pnda/jupyter/lib/python3.4/site-packages/sparkmagic/livyclientlib/sparkcontroller.py in add_session(self, name, endpoint, skip_if_exists, properties)
     84         session = self._livy_session(http_client, properties, self.ipython_display)
     85         self.session_manager.add_session(name, session)
---> 86         session.start()
     87 
     88     def get_session_id_for_client(self, name):

/opt/pnda/jupyter/lib/python3.4/site-packages/sparkmagic/livyclientlib/livysession.py in start(self)
    131             except LivyClientTimeoutException:
    132                 raise LivyClientTimeoutException(u"Session {} did not start up in {} seconds."
--> 133                                                  .format(self.id, conf.livy_session_startup_timeout_seconds()))
    134 
    135             html = get_sessions_info_html([self], self.id)

LivyClientTimeoutException: Session 4 did not start up in 60 seconds.

Is there a way to modify this to only scala?

**Comment by aggFTW** [comment]
Not out of the box, no. You would have to debug why livy is failing to create a python session.
