### ISSUE TITLE
Use authenticated Jupyter user for Livy

### ISSUE THREAD

**Issue by trsmith2** [jupyter-incubator/sparkmagic#429]
Is it possible to configure Jupyter/sparkmagic such that the YARN application that Livy creates is run as the authenticated Jupyter user? I.e. to use impersonation.

**Comment by aggFTW** [comment]
Not yet.

**Comment by tomz** [comment]
@aggFTW what's the reason for closing this issue? - this is a useful (and for some users a must have) feature, especially for JupyterHub.
