### ISSUE TITLE
Unable to manage sessions after shutting down notebook

### ISSUE THREAD

**Issue by mrunmayeejog** [jupyter-incubator/sparkmagic#430]
I have installed sparkmagic and creating sessions with %manage_spark.
I refered to [similar issue](https://github.com/jupyter-incubator/sparkmagic/issues/387) and set heartbeat timeout to 10 so that my sessions are stopped if I shutdown/close&halt my notebook.
But without this setting:
If I close my notebook without shutting it down I see application running in yarn and my livy session as idle in livy UI.
However if I shutdown the notebook I am not able to delete the previous sessions using %manage_spark as I am not able to see these in manage sessions option. It says No sessions to manage in Manage session tab nor anything in Manage endpoints tab. Where as I see in Livy UI session as idle. Nor the application stops in yarn. I need to manually kill it using yarn kill. 
If I do not set the heartbeats parameter do I need to manually kill applications every time? As not able to see in %manage_spark magic for the same(previously shutdown notebook). Otherwise after how long are these sessions and running applications in yarn stopped? 

I am using jupyterhub 0.7.0 and jupyter 4.2.1.

**Comment by aggFTW** [comment]
>If I close my notebook without shutting it down I see application running in yarn and my livy session as idle in livy UI.
That is the right behavior. You would need to close and halt for the kernel to send the session stop command to livy.

>It says No sessions to manage in Manage session tab nor anything in Manage endpoints tab.
What happens if you add the endpoint again. Do the sessions appear?

**Comment by mrunmayeejog** [comment]
That is the right behavior. You would need to close and halt for the kernel to send the session stop command to livy. - Even with close and halt it appears in yarn.

What happens if you add the endpoint again. Do the sessions appear? - Yes I can add new/same endpoint then from manage endpoints can perform clean up.

**Comment by aggFTW** [comment]
Yes, you need to add the endpoint again for the sessions to appear. Actually, I understand now, sorry. Only sessions created by sparkmagic kernels are deleted by the kernels. If you are using the widget version, you need to clean up yourself via the widgets.

Thanks!
