### ISSUE TITLE
When installing sparkmagic in anaconda3, both pysparkkernel and pyspark3kernel appear to run python3.

### ISSUE THREAD

**Issue by lstillwe** [jupyter-incubator/sparkmagic#433]
I have installed sparkmagic in anaconda3 (with python3) and in a python 2 virtual env. Jupyter notebook offers both kernels but appears to be running python3 in both.

**Comment by aggFTW** [comment]
You need to configure Livy to use the right python interpreter per livy session type. Please refer to the livy documentation for it.
