### ISSUE TITLE
DataFrameParseException: Cannot parse object as JSON: '['b\'{

### ISSUE THREAD

**Issue by mpekalski** [jupyter-incubator/sparkmagic#436]
pyspark3 kernel
livy 0.4.0
python 3.5 on a cluster
python 3.6 locally 
sparkmagic 0.12.5
notebook 5.4.0

We have upgraded our cluster with Ambari which also bumped up the Livy's version to 0.4.0, then we had some problems with starting new spark sessions, in pySpark3 kernel, as we want to use Python 3 and the parameters passed in config had to include 
(according to https://github.com/jupyter-incubator/sparkmagic/pull/421/files/2d15016e77f89074b6dfc2c54e85b2c9abf1940c)
```
"conf": {
 "spark.pyspark.python": "python3", 
}
```

Now everything runs ok, but one thing, exporting from %%spark to %%local, with `%%spark -o df`

I get an error
```
DataFrameParseException: Cannot parse object as JSON: '['b\'{....
```

With previous version of livy it was enough to set 
```
spark.yarn.appMasterEnv.PYSPARK3_PYTHON = /usr/bin/python3
```
but now I do not know what to do, seems like sparkmagic does not recognize it has to use python3 for outputing. 

Runnig sys.version on a cluster, via livy, shows
'3.5.2 (default, Aug 18 2017, 17:48:00) \n[GCC 5.4.0 20160609]'

**Comment by aggFTW** [comment]
Sparkmagic doesn't officially support livy 0.4.0 yet...

That said, I think this may be happening because of an incorrect sql command being sent: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/sqlquery.py#L81

Note that python 3 doesn't encode the results when it prints them: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/sqlquery.py#L42

Maybe try debugging from that?

**Comment by mpekalski** [comment]
The issues is that `session.kind` in `sparkmagic/livyclientlib/sparkstorecommand.py` has 
```
session.kind = 'pyspark'
```

but when I print configuration with `%%info` it shows `kind:"pyspark3"`

In `kernel/kernelmagics.py` I have created a magic to print language and session.kind
```
self.ipython_display.html(u"Current session language: <tt>{}</tt><br>Kind: <tt>{}</tt><br>".format(self.language, get_livy_kind(self.language)))
```
and it prints 
```
Current session language: python3
Kind: pyspark3
```

**Comment by mpekalski** [comment]
also when debugging `sparkmagic/livyclientlib/sparkstorecommand.py` I see that the kind has a value of `pyspark` not `pyspark3` as suggested by the tests in my previous comment. So it gets overwritten somewhere.

```
ipdb> session.properties
{'driverMemory': '1G', 'executorCores': 4, 'kind': 'pyspark', 'conf': {'spark.pyspark.python': 'python3', ...}
```

**Comment by mpekalski** [comment]
When I run the `%%spark add` command with language `python3` the kind seems to be set to `pyspark3`, which I would expect, but then the connection does not get created. I looked into the livy's logs and there it states that the **kind is invalid**

```
<<<"Invalid kind: py...est[\\"kind\\"])">>>state":"idle"
``

**Comment by harschware** [comment]
Hi @aggFTW 

> Sparkmagic doesn't officially support livy 0.4.0 yet...

I assumed it did because I did not see anything in README about version compatibility.  Is 0.4.0 on the roadmap?

**Comment by aggFTW** [comment]
We would welcome a contribution to make it compatible with livy 0.4.0, or even 0.5.0. At the moment, I don't have time to work on it. We did have a PR sent that seems to have addressed it almost completely (don't recall if the scenario you are reporting here as broken was tested or not).

@taoliseki is that PR ready to be merged? Could you comment on whether that PR addressed this bug_

**Comment by mpekalski** [comment]
In the end #421 worked for me, it did not work in all cases as it was overriding some conf parameters, but I have submitted another #437. Sorry for submitting a new PR but I do not know how to modify someone else's PR.

After applying #437 something like this workf for me
```
%%spark config
{"driverMemory":"1G",
 "executorCores":4,
 "conf": {"spark.pyspark.python": "python3",
          "spark.jars.packages": "com.databricks:spark-avro_2.11:4.0.0"
}}

%spark add -s $username -l python3 --url=https://my_url/gateway/default/livy2/v1 --user=$username --password=$password
```

**Comment by ldesmet** [comment]
Greetings everyone,

I have difficulties to use spark magic with PySpark3. At the begining, I had this log error : 


```
The code failed because of a fatal error:
	Invalid status code '400' from https://XXXX.azurehdinsight.net/livy/sessions with error payload: "Invalid kind: pyspark3 (through reference chain: org.apache.livy.server.interactive.CreateInteractiveRequest[\"kind\"])".

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.
```


But after using the pull request at the begining oh this thread, it did work. Unfortunately, I think there is no more connection with my cluster XXXXX. Indeed, when I want to import a library such as tensorflow, it did not find it, and i'm sure it is well installed on the cluster.

Could you help me with that please ?

Thanks everyone
