### ISSUE TITLE
sparkmagic ERROR:Cannot parse object as JSON

### ISSUE THREAD

**Issue by twterry** [jupyter-incubator/sparkmagic#471]
%%sql
select a,count(1) from test_table group by a

An internal error was encountered.
Please file an issue at https://github.com/jupyter-incubator/sparkmagic
Error:
Cannot parse object as JSON: '[u'{"a":1,"count(1)":5}', u'{"a":-1,"count(1)":6}', u'']'

**Comment by karth295** [comment]
I hit this as well with an even simpler repro:

```
%%sql
select 1
```

```
An internal error was encountered.
Please file an issue at https://github.com/jupyter-incubator/sparkmagic
Error:
Cannot parse object as JSON: '[u'{"1":1}', u'']'
```

Environment:
* Spark 2.2.1, Java 8, Hadoop 2.8.4
* `pip install sparkmagic` (resolved to `0.12.5`)
* Had to downgrade pandas due to #458

**Comment by karth295** [comment]
Looks like the same error as in #445

**Comment by RobertAron** [comment]
I'm having this issue as well. It seems to only effect the `spark` kernel and not the `pyspark` one.

```scala
val someDF = Seq(
  (8, "bat"),
  (64, "mouse"),
  (-27, "horse")
).toDF("number", "word")
```
```terminal
%%spark -o someDF
```
```error
An internal error was encountered.
Please file an issue at https://github.com/jupyter-incubator/sparkmagic
Error:
Cannot parse object as JSON: '['{"number":8,"word":"bat"}', '{"number":64,"word":"mouse"}', '{"number":-27,"word":"horse"}', '']'
```

Has this issue been addressed yet? I can't seem to find any issues talking about it.

**Comment by Tagar** [comment]
We have same issue with `pyspark` not just `spark`

**Comment by dmnapolitano** [comment]
Same issue here with `pyspark` notebooks, sorry to say.  For reference:

```python
%%info

Current session configs: {'conf': {'spark.yarn.appMasterEnv.PYTHONUSERBASE': '<dir>', 'spark.yarn.appMasterEnv.PYSPARK_PYTHON': '/usr/lib/anaconda3/bin/python3'}, 'kind': 'pyspark'}
```

```python
%%sql -o df
select 1, 2, 3

An internal error was encountered.
Please file an issue at https://github.com/jupyter-incubator/sparkmagic
Error:
Cannot parse object as JSON: '['b\'{"1":1,"2":2,"3":3}\'']'
```

Python 3.6.5, Java 8 (OpenJDK) on CentOS 7.4.  I'd be happy to help out however I can.  Thanks 😄

**Comment by mhuang74** [comment]
Filtering empty string in array after *split* seems to have fixed the problem for me:

```
def records_to_dataframe(records_text, kind, coerce=None):
    if records_text in ['', '[]']:
        strings = []
    else:
        # fix https://github.com/jupyter-incubator/sparkmagic/issues/471
        strings = filter(None, strings)
    try:
        data_array = [json.JSONDecoder(object_pairs_hook=OrderedDict).decode(s) for s in strings]
```

**Comment by alexmnyc** [comment]
Same here

**Comment by itamarst** [comment]
The code now has a `.strip()` which should strip leading/ending newlines, which probably explains why I can't reproduce this. So going to say it's fixed. Please re-open if you're still having issues.
