### ISSUE TITLE
Question: Using visualization widget in a Python environment

### ISSUE THREAD

**Issue by Nithanaroy** [jupyter-incubator/sparkmagic#478]
When using `sparkmagic` in Jupyter, it generates this nice interactive visualization of a dataframe. (full example at from https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Pyspark%20Kernel.ipynb). How to achieve the same visualization controls for a normal python notebook having pandas dataframe objects without any Spark code?

![jupyter widget visualization](https://i.stack.imgur.com/8VzJX.png)

No matter what I install the dataframe when viewed in a cell, shows up only as a table. 
Asked the same at https://stackoverflow.com/questions/52234432/interactive-multi-chart-widget-in-jupyter-notebook-for-pandas-dataframe but no one answered.
Thank you.

**Comment by apetresc** [comment]
That visualization is done through the autovizwidget library, which is separate from sparkmagic even though it's part of this same repository. You can certainly invoke it in a normal Python kernel, like so: https://github.com/jupyter-incubator/sparkmagic/blob/master/autovizwidget/examples/autoviz.ipynb

Hope that helps :)
