### ISSUE TITLE
System-wide config for JupyterHub

### ISSUE THREAD

**Issue by user919lx** [jupyter-incubator/sparkmagic#479]
I am using Jupyterhub for multiple  user.And I have to copy the sparkmagic config file to every user's home directory.When I want to modify some config , I have to copy it again.
Is there a way to set a system wide config so that I don't need to copy sparkmagic config file to every user in JupyterHub?

**Comment by xuelangZF** [comment]
Same problem.

**Comment by ericdill** [comment]
Globally set the SPARKMAGIC_CONF_DIR environmental variable to be where you have this config folder.

https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/utils/constants.py#L7-L8

**Comment by user919lx** [comment]
> Globally set the SPARKMAGIC_CONF_DIR environmental variable to be where you have this config folder.
> 
> https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/utils/constants.py#L7-L8

Thank you for help.That solve my problem.

write that in jupyterhub_config.py

c.Spawner.environment = {
    "SPARKMAGIC_CONF_DIR": "/xxx",
    "SPARKMAGIC_CONF_FILE": "xxx.json"
}
