### ISSUE TITLE
Issue with SESSION_KIND for the Pyspark3 kernel

### ISSUE THREAD

**Issue by rohitp27** [jupyter-incubator/sparkmagic#490]
Hi, I was trying to use the pyspark3 kernel with a livy server set up and couldn't work with the kernel. I found that the session-kind being passed [in the constants here](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/utils/constants.py) is pyspark3 whereas the latest livy version does not support 'pyspark3' as a valid 'kind' parameter. It just uses 'pyspark'.

Is there any ongoing effort to fix this? I would like to work on this.

**Comment by itamarst** [comment]
This is now fixed in `master`. I will try to do a release soon.

**Comment by itamarst** [comment]
I have released 0.12.8 which will hopefully fix this.
