### ISSUE TITLE
Disable %%configure sparkmagic command

### ISSUE THREAD

**Issue by sdandey** [jupyter-incubator/sparkmagic#495]
Is there a way to disable specifically %%configure magic command?  I want to restrict users from using this magic to set proxyUser explicitly.  Does sparkmagic provide any capabilities to achieve this functionality?

**Comment by zuoakang** [comment]
woo, This has not been resolved yet? It seems that only do it by yourself.

**Comment by sdandey** [comment]
I'm closing this ticket.  

I resolved this myself by making changes to the %%configure magic code tp re-write the proxyUser info with process id.
