### ISSUE TITLE
Can not plot sql result in Jupyter Lab

### ISSUE THREAD

**Issue by BillyRen** [jupyter-incubator/sparkmagic#500]
![image](https://user-images.githubusercontent.com/2060589/50512971-01bab780-0ad0-11e9-887d-e547785ab7a0.png)

When I ran %%sql magic in Jupyter Lab, there was no auto plot function available and it only showed the result in table.

I'd like to know how could I fix this?

**Comment by xiancode** [comment]
may be you should install plotly  extension .
https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension

**Comment by tmrlvi** [comment]
Had same problem. Plotly extension solved it.

Plotly extension is now at https://www.npmjs.com/package/jupyterlab-plotly
(you can run `jupyter labextension install jupyterlab-plotly`)
