### ISSUE TITLE
sparkmagic output html table

### ISSUE THREAD

**Issue by Tagar** [jupyter-incubator/sparkmagic#512]
![image](https://user-images.githubusercontent.com/3013418/52385812-8ccc8d00-2a40-11e9-9da9-79c7fafc42f5.png)

Is there is a way to actually display an html output, like it works without `%%spark` ?

**Comment by Tagar** [comment]
@itamarst please have a look if there is a way to fix this ? 

thanks!

**Comment by winston-zillow** [comment]
Same in pyspark kernel, HTML outputs are not displayed but the HTML codes printed. Also the pandas `DataFrame`s (note: **not** the pyspark DataFrame) are not being rendered prettified, even using `display()` or `display_html()`.

Whereas running regular kernel (even in the same instance/python env) will render correctly.

<img width="1617" alt="Screenshot 2023-03-28 at 5 33 54 PM" src="https://user-images.githubusercontent.com/26907141/228397547-709ba88e-c001-4923-8321-14bfaab3252f.png">
<img width="1623" alt="Screenshot 2023-03-28 at 5 33 38 PM" src="https://user-images.githubusercontent.com/26907141/228397554-bbde73a8-69c6-4126-9316-03fb5c64a249.png">

**Comment by winston-zillow** [comment]
@devstein please take a look. This seems an annoying problem.

**Comment by devstein** [comment]
@winston-zillow Thanks for the example. As demonstrated in first example. Sparkmagic naively renders the response from Livy, which is the `{ 'text/html': '<h1>H1</h1>' }` JSON. This should be fixable. Are you open to contributing?


The second example is much tricky. Your local notebook has access to the raw pandas dataframe while Sparkmagic has to parse the dataframe values from the JSON string returned from Livy. This is what the `%%pretty` magic attempts to do.
