### ISSUE TITLE
PySpark3 kernel doesn't work with Livy 0.5.0

### ISSUE THREAD

**Issue by squidnee** [jupyter-incubator/sparkmagic#515]
Bringing up an EMR cluster with Livy 0.5.0 leads to the following 400 error: 
"Invalid kind: pyspark3 (through reference chain: org.apache.livy.server.interactive.CreateInteractiveRequest[\"kind\"])". 

It appears that PySpark3 is not supported by Livy 0.5.0. For reference, see this page:
https://github.com/apache/incubator-livy/blob/master/docs/rest-api.md#pyspark

I am currently in a situation where I need to use both Livy 0.5.0 with Sparkmagic, so I have created a patch that removes the PySpark3 kernel for my own purposes. I was wondering if this would be something worth pushing upstream? Or, if it shouldn't be removed, can you comment on the long-term maintenance plans for the PySpark3 kernel, or perhaps ways to modularize it so that users of Livy 0.5.0 have a path forward?

**Comment by rohitp27** [comment]
Hey @squidnee, this might be similar to the issue I have raised here : https://github.com/jupyter-incubator/sparkmagic/issues/490 

I changed the session-kind for SESSION_KIND_PYSPARK3 to the same value as for SESSION_KIND_PYSPARK, and configured the EMR to use python3 as the default python version (I think this is also a default behaviour for the latest installations for spark, need to check that). This seems a bit hacky but works for me atm.

Have you maybe taken a cleaner approach to this?

**Comment by squidnee** [comment]
Hi @rohitp27, could you confirm that changing the SESSION_KIND_PYSPARK3 variable to SESSION_KIND_PYSPARK still uses the PySpark3 kernel? From my understanding it just changes the kernel to the PySpark kernel (which IIRC uses Python 2.7). I believe that the solution I ended up pursuing involved altering the PySpark environment to accept Python 3.6 and greater.

**Comment by Tagar** [comment]
Btw, Livy now has 0.6 release 
https://lists.apache.org/thread.html/70c715f6394f06f0a49f76671b0f57cd1cdca35f7862a9ad2cf87fd7@%3Cdev.livy.apache.org%3E 

Although this issue still stand in the new release as well

**Comment by juliusvonkohout** [comment]
#528 I have provided a pull request that fixes the encoding for pyhon3 via kind pyspark.

Furthermore just use park.pyspark.python as shown below to select the python executable.

`%%configure -f
{   
    "conf":{
    "spark.driver.memory":"600M",
    "spark.executor.memory":"1024M",
    "spark.pyspark.python":"python3",
    "spark.executor.cores":"1",
    "spark.cores.max":"1"}
}`

**Comment by itamarst** [comment]
Fixed by #540.

**Comment by itamarst** [comment]
I have released 0.12.8 which will hopefully fix this.

**Comment by jaipreet-s** [comment]
Hi @itamarst , this is great!

I see the release on [conda-forge](https://anaconda.org/conda-forge/sparkmagic) for Linux still points to   v0.12.1 but [PyPI](https://pypi.org/project/sparkmagic/0.12.8/) is on v0.12.8. Is PyPI the recommend channel to consume sparkmagic?

**Comment by itamarst** [comment]
Conda-Forge packages for 0.12.8 are in progress and will be out soon, thanks to @ericdill
