### ISSUE TITLE
Release on Anaconda missing PySpark3

### ISSUE THREAD

**Issue by jaipreet-s** [jupyter-incubator/sparkmagic#516]
The latest release of Anaconda on the Anaconda channel is missing PySpark3. The conda-forge channel appears to be fine.

https://anaconda.org/anaconda/sparkmagic/files

**Comment by tylerxXx** [comment]
Hi, I couldn't install sparkmagic via anaconda, got a PackagesNotFoundError. Did you install sparkmagic successfully?

**Comment by itamarst** [comment]
I suggest filing issues in the anaconda repository, the packaging for anaconda happens outside of this repo: https://github.com/AnacondaRecipes/sparkmagic-feedstock/

**Comment by itamarst** [comment]
I have released 0.12.8 which will hopefully fix this.
