### ISSUE TITLE
Default spark master while creating SparkSession

### ISSUE THREAD

**Issue by devender-yadav** [jupyter-incubator/sparkmagic#524]
Sparkmagic will automatically create `SparkContext` and `SparkSession`. What's default spark master used - local or yarn? Similarly other properties while creating `SparkSession` from `SparkSession.builder()`.

Can I configure these value?

**Comment by apetresc** [comment]
These things are controlled by Livy, not Sparkmagic. Check out [the relevant section of `livy.conf`](https://github.com/apache/incubator-livy/blob/master/conf/livy.conf.template#L42) and the [Livy `/sessions` POST API endpoint parameters](http://livy.incubator.apache.org./docs/latest/rest-api.html#post-sessions) (the latter of which can be set through `%%configure` in Sparkmagic).
