### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#53]
For Scala and R support, we may want to look at http://pygments.org/languages/

For SQL support, look at @alope107's solution in https://github.com/alope107/spark-sql-magic/commit/34b4d864cdaaa0cc56481b3045a66bf679141f78

**Comment by msftristew** [comment]
Scala support is in CodeMirror through this file, clike.js: https://github.com/codemirror/CodeMirror/blob/master/mode/clike/clike.js

However, when I set the mode to `clike` for Scala, I don't get correct highlighting/text editing behavior (none of the correct keywords are highlighted, and default indentation is incorrect unless I put a semicolon at the end of all my lines).  Going to keep investigating.

**Comment by msftristew** [comment]
Python taken care of through #104

**Comment by msftristew** [comment]
In my testing, Scala isn't working even if I set the codemirror mode to "clike" and the MIME type to `text/x-scala`.  For some reason CodeMirror isn't "getting" that what I type in is supposed to be Scala code and is instead applying some very simple, stupid syntax highlighting to it (i.e. only highlighting equals signs and integer literals).  Can keep looking at this later.

**Comment by aggFTW** [comment]
Hey @msftristew, any updates for this?

**Comment by msftristew** [comment]
Scala and Python syntax highlighting are both working great.  I haven't tested out SQL but it should be easy (@alope107's solution should be fine here)

**Comment by msftristew** [comment]
There's an issue.  See https://github.com/ipython/ipython/issues/7548

It looks like only cell magics trigger magics syntax highlighting. I don't think that syntax-highlighted line magics are supported.  This means that our SQL and Hive commands need to be %%sql and %%hive in order for syntax highlighting to kick in -- %sql and %hive won't work.

**Comment by aggFTW** [comment]
Let's go with that for now and we'll investigate line magics in parallel.

**Comment by msftristew** [comment]
Arguably all of the "magics" in our Spark kernel are cell magics, not line magics. So it breaks with convention less if we move to a model where `%%sql`, `%%hive`, `%%config`, etc. are the "normal" way to call things.

**Comment by msftristew** [comment]
Still need to do this :(

**Comment by msftristew** [comment]
So, I have a branch going (kerneljs) which is supposed to fix SQL syntax highlighting.  As it stands, on my Windows machine, SQL syntax highlighting works for the first cell but fails with an error message in the console for the rest.

![image](https://cloud.githubusercontent.com/assets/13972471/13826165/54ae7532-eb73-11e5-926e-0a19d9d7b528.png)

![image](https://cloud.githubusercontent.com/assets/13972471/13826180/6579ac9c-eb73-11e5-8532-c968f78fa7cf.png)

I think [this](https://github.com/jupyter/notebook/pull/1017) PR to jupyter/notebook (which hasn't made it into an official release yet) is supposed to fix this issue?  Maybe?  I don't know.
