### ISSUE TITLE
Error sending http request and maximum retry encountered..

### ISSUE THREAD

**Issue by tengpeng** [jupyter-incubator/sparkmagic#533]
I am having this issue when I connect to my Spark kernel via Livy.

```
The code failed because of a fatal error:
	Error sending http request and maximum retry encountered..

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.
```

I checked my `config` file which looks fine.

Then I checked Livy endpoint which shows it is reachable and no sessions are created.

```
{
  "kernel_python_credentials" : {
    "username": "",
    "password": "",
    "url": "http://xxx:899x",
    "auth": "None"
  },
  "kernel_scala_credentials" : {
    "username": "",
    "password": "",
    "url": "http://xxx:899x",
    "auth": "None"
  },
  "kernel_r_credentials": {
    "username": "",
    "password": "",
    "url": "http://xxx:899x",
    "auth": "None"
  }
}

```

I then checked Livy service by post request manually and I have successfully submit Spark jobs to our cluster.

Where else should I check?

**Comment by jaganreddy62** [comment]
hi peng,

Im facing issue. can you please let me know how are able to solve this.

Thanks in advance

**Comment by boegel** [comment]
@tengpeng Did you manage to solve this issue? If so, please share how...

![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by tengpeng** [comment]
Honestly, I deleted everything and reinstalled everything. Then problem solved. 😆

**Comment by boegel** [comment]
The problem in my case was the Livy wasn't actually running at all, check with `livy-server status`

**Comment by kyprifog** [comment]
I'm getting this error, however the livy server is running and I can actually submit jobs to it manually using the Livy Rest API, which is a bit perplexing.
