### ISSUE TITLE
How to share data from pyspark kernel to local?

### ISSUE THREAD

**Issue by devender-yadav** [jupyter-incubator/sparkmagic#536]
For example, I did some processing in spark and finally create a dictionary and I want to use that dictionary in local mode (%%local) to plot chart. how do I access variables created in pyspark kernel in local mode?

**Comment by apetresc** [comment]
You can use the `-o` flag to import a Spark dataframe into the local kernel (it will be implicitly converted to a Pandas dataframe, and it will be truncated to a configurable number of maximum rows).

There's [an open PR](#431) to extend the `-o` flag to any data type, not just a Spark Dataframe, but it hasn't been merged yet.

**Comment by devender-yadav** [comment]
@apetresc  is it using pyarrow while converting to pandas df?
