### ISSUE TITLE
Give pandas df back to user when user runs sql query

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#54]
The pandas df being constructed is not being passed back to the user for the user to play with.

So, user does something like:

`%spark -c sql SELECT * FROM table`

and even though the result is being constructed into a pandas df, user cannot visualize it.

Instead, a user could do something like:

`%spark -c sql -v myDf SELECT * FROM table`

and result could be available in `myDf`.

We should discuss the syntax before implementing this. Pinging @ellisonbg

**Comment by ellisonbg** [comment]
The R magic uses `-o` or `--output` for this, might want to follow that
convention.

On Fri, Dec 4, 2015 at 3:14 PM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> The pandas df being constructed is not being passed back to the user for
> the user to play with.
>
> So, user does something like:
>
> %spark -c sql SELECT * FROM table
>
> and even though the result is being constructed into a pandas df, user
> cannot visualize it.
>
> Instead, a user could do something like:
>
> %spark -c sql -v myDf SELECT * FROM table
>
> and result could be available in myDf.
>
> We should discuss the syntax before implementing this. Pinging @ellisonbg
> <https://github.com/ellisonbg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter-incubator/sparkmagic/issues/54>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
That makes sense. Thanks Brian!
