### ISSUE TITLE
Where is pyspark3kernel?

### ISSUE THREAD

**Issue by morganhferry** [jupyter-incubator/sparkmagic#556]
We replaced our JupyterHub instances during an upgrade last night. Afterward, we noticed a failure in part of our script indicating that the pyspark3kernel didn't exist in the sparkmagic folder. We tried using conda as well as pip to install sparkmagic - in both cases, the pyspark3kernel does not exist. Was it recently removed for some reason? Forgive me if I'm totally missing something.

**Comment by itamarst** [comment]
A number of changes in Livy mean that there's no longer two different ways of indicating Python version to Livy, you always use the same way on the SparkMagic side. Choice of Python 2 vs 3 is now something you need to configure on the Livy side:

> Like pyspark, if Livy is running in local mode, just set the environment variable. If the session is running in yarn-cluster mode, please set spark.yarn.appMasterEnv.PYSPARK_PYTHON in SparkConf so the environment variable is passed to the driver.

Just use `pysparkkernel` and it'll work.

I did however notice a bug that resulted from this removal, so just filed it: #557.

**Comment by morganhferry** [comment]
Thanks a lot! That makes sense. We see that value in our newest Livy instal and will update that. Appreciate the quick response.
