### ISSUE TITLE
Support text/html MIME type.

### ISSUE THREAD

**Issue by imback82** [jupyter-incubator/sparkmagic#562]
Currently only the `image/png` and `text/plain` are supported:

https://github.com/jupyter-incubator/sparkmagic/blob/cf06e20553df2e2157d5d95db6a167a62145963b/sparkmagic/sparkmagic/livyclientlib/command.py#L85-L93

The above and the following can be updated to support the `text/html` type.
https://github.com/jupyter-incubator/sparkmagic/blob/161b681e272a1dab6fc60547ea771305b84295d7/sparkmagic/sparkmagic/magics/sparkmagicsbase.py#L47-L50

Please let me know if this is the right approach. I will create a PR to address this.

**Comment by imback82** [comment]
cc: @rapoth, @suhsteve

**Comment by itamarst** [comment]
If Livy can return text/html then sure, sounds like a thing that might be useful.
