### ISSUE TITLE
Plotting charts using matplotlib

### ISSUE THREAD

**Issue by devender-yadav** [jupyter-incubator/sparkmagic#564]
I am using pyspark kernel with Python3.

Looking at the example notebook - https://github.com/jupyter-incubator/sparkmagic/blob/161b681e272a1dab6fc60547ea771305b84295d7/examples/Pyspark%20Kernel.ipynb

>You can also have images rendered on the server, and then display them locally. This prevents the need to ship large amounts of data locally to do visualizations. First, we render a PNG, in this case using matplotlib

Code running on spark side 

```
import pandas as pd

df = pd.DataFrame({
    'name':['john','mary','peter','jeff','bill','lisa','jose'],
    'age':[23,78,22,19,45,33,20],
    'gender':['M','F','M','M','M','F','M'],
    'state':['california','dc','california','dc','california','texas','texas'],
    'num_children':[2,0,0,3,2,1,4],
    'num_pets':[5,1,0,5,2,2,3]})

df.plot()
```

Now, I am trying to plot chart in local mode,
```
%%local
%matplot plt
```

Error:

**UsageError: Line magic function `%matplot` not found.**

That example is outdated. So, how can I plot chart in the latest version?

**Comment by devender-yadav** [comment]
@itamarst Can you please have a look in this. I didn't find any updated example for this.

**Comment by itamarst** [comment]
I think you want to omit the `%%local` line?

**Comment by devender-yadav** [comment]
@itamarst thanks with 0.12.9 its working fine. 

    %matplot plt


Finally, EMR updated sparkmagic version to 0.12.9
