### ISSUE TITLE
Sparkmagic session dies if cell runs longer than `livy.server.session.timeout`

### ISSUE THREAD

**Issue by jpugliesi** [jupyter-incubator/sparkmagic#566]
Hello - I'm using sparkmagic to execute long-running spark jobs, and running into an issue where the sparkmagic livy session dies if the submitted spark job runs longer than the configured livy.server.session.timeout. The error manifests as the usual:
```
An error was encountered:
Invalid status code '404' from http://my-livy-server:8998/sessions/38 with error payload: {"msg":"Session '38' not found."}
```

I've seen solutions elsewhere online that suggest increasing the configured `livy.server.session.timeout` - this seems unideal in that it allows truly inactive livy sessions to persist longer (and potentially consume resources).

1. Does the sparkmagic session heartbeat thread not keep the session alive if a cell runs longer than the livy session's timeout?
2. Is there a way to avoid this timeout/maintain a heartbeat without increasing the `livy.server.session.timeout`?

Appreciate the help

**Comment by itamarst** [comment]
Thanks for the question! Will try to read code on Friday and see if anything leaps out at me, but as first pass increasing timeout seems like short-term workaround.

**Comment by itamarst** [comment]
So it looks like by default the heartbeat in sparkmagic is disabled, and to change it you need to change the configuration parameter `livy_server_heartbeat_timeout_seconds`. Can you try setting that to some number like 10 and see if it solves your problem?

It may be that the heartbeat should be enabled by default...

**Comment by jpugliesi** [comment]
@itamarst Thanks very much for looking into this - I currently had `livy_server_heartbeat_timeout_seconds` set to 0 seconds as provided in [`example_config.json`](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/example_config.json) - I now see in the code [that heartbeat is turned off if this config is set to 0](https://github.com/jupyter-incubator/sparkmagic/blob/634ee0d356b8e9685fe006739b7543149cfef374/sparkmagic/sparkmagic/livyclientlib/livysession.py#L57-L69)

I'll try increasing to 10 seconds and will see if it solves the problem. Thanks again!

**Comment by jpugliesi** [comment]
@itamarst Setting the `livy_server_heartbeat_timeout_seconds` indeed enables the heartbeat, but as a note to future readers: do not set the `livy_server_heartbeat_timeout_seconds: 10` if you have set `hearbeat_retry_seconds: 10` seconds because this will of course lead to a sort of race-condition where the timeout and retry are both 10 seconds.  `livy_server_heartbeat_timeout_seconds` should be greater than `hearbeat_retry_seconds`

**Comment by itamarst** [comment]
Re-opening because arguably the default shouldn't be 0.

**Comment by Tagar** [comment]
Yep seems like a good idea to heartbeat by default

Thanks
