### ISSUE TITLE
No iPython Error Thrown When configuration.spark_statement_errors_are_fatal() is True

### ISSUE THREAD

**Issue by devstein** [jupyter-incubator/sparkmagic#578]
Refer to original comment https://github.com/jupyter-incubator/sparkmagic/pull/519#issuecomment-539150332

The current implementation in https://github.com/jupyter-incubator/sparkmagic/pull/519 doesn't seem to raise an exception when executing a `jupyter` notebook with `papermill`. In my notebook it only shut down the `livy` session

- `shutdown_session_on_spark_statement_errors`
- `spark_statement_errors_are_fatal`

I used to the following code to verify my configuration was correct
```python
from sparkmagic.utils import configuration

print(configuration.shutdown_session_on_spark_statement_errors()) # True
print(configuration.spark_statement_errors_are_fatal()) # True
```

**Comment by PedroRossi** [comment]
I also have the same issue when using papaermill with the sparkkernel.

I tried removing the `wrap_unexpected_exceptions` decorator from the `sparkmagic.kernels` (https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/kernels/kernelmagics.py#L219) and it fixed the error throw on the sparkkernel, I also noticed that this decorator is only used on the `sparkmagic.kernels` and not on the `sparkmagic.magic` (https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/magics/remotesparkmagics.py#L68), is this function really needed to some other motive that I am not understanding? @itamarst

**Comment by devstein** [comment]
@itamarst Any updates on this?

**Comment by itamarst** [comment]
Hi,

Sorry for the delay, I hope to get some work done on SparkMagic in the next couple of weeks. If someone submits a PR (with a test) that'll speed things up.

**Comment by devstein** [comment]
@itamarst Happy to make a PR with a test for this, but do you mind answering @PedroRossi question?

**Comment by itamarst** [comment]
I don't yet know the code well enough to answer offhand... I'll answer when I next to maintenance, if you don't figure it out.
