### ISSUE TITLE
Restructure repos

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#58]
We should create other repos for a Livy client, a configuration getter, a logger, and etcetera. Then we should put our python files into folders that make actual sense.

In doing this, we might want to add docstring comments for public methods in every repo.

**Comment by aggFTW** [comment]
Also, all package names should be all lowercase (RemoteSparkMagics) doesn't adhere to that.

**Comment by aggFTW** [comment]
In the end, we should have these repos (we can decide names later if we want to) and every repo would be logically organized in folders. We may want to organize into folder first and then break it up into repos.

1. sparkmagic (depends on {sparkmagicconfiguration, sparkmagiclogger})
2. sparkmagickernels (depends on {sparkmagic, sparkmagicconfiguration, sparkmagiclogger, pandasautomaticvisualization})
3. sparkmagicconfiguration (depends on {})
4. sparkmagiclogger (depends on {})
4. pandasautomaticvisualization (depends on {})
5. livyclient (depends on {})

**Comment by msftristew** [comment]
I don't know if we necessarily need 6 repos, but I'll investigate :)

**Comment by msftristew** [comment]
Should this be closed?

**Comment by aggFTW** [comment]
No, we need to break the codebase into different repos.
