### ISSUE TITLE
Question: Sparkmagic UI widgets customization 

### ISSUE THREAD

**Issue by ikiw** [jupyter-incubator/sparkmagic#584]
Hi Team,

We are exploring sparkmagic and thought of customizing the UI widgets in sparkmagic. Is there any recommended approach to do ?  Find the sparkmagic widgets implemented in python. Is it feasible to extend the widgets UI using JavaScript/CSS ?Any pointers on this will be great ? 

Say if something has to be modified in add endpoint widget, is there a way to only override the rendering of dom that addendpointwidget.py does ?

**Comment by itamarst** [comment]
The underlying implementation uses `ipywidgets`, which does e.g. have some CSS customization possible: https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html

If you want full customization you'd probably have to write your own... but it ought to be possible to create alternative widgets that call the same Python APIs.
