### ISSUE TITLE
Revise API

### ISSUE THREAD

**Issue by alope107** [jupyter-incubator/sparkmagic#6]
Consolidate magics and commands.  Clean up UX.

**Comment by alope107** [comment]
I propose that we merge the current two magics, `%sparkconf` and `%%sparkmagic` into a single magic `%%spark`.  This magic supports all the same functionality of the other current magics through a very similar argument passing style. 
If the user omits a required argument, they are prompted for it. In the notebook, this prompt takes the form of IPython widgets (a drop-down selection for language and client, text field for connection string etc). Entering `%%spark` without any arguments thus gives a simple GUI that allows the user to perform any remote spark task without needing to learn the command syntax.
On the command line, we can decide whether it makes more sense to have textual prompts to input the missing arguments or to display an error message.
These proposed changes are designed to make it as easy as possible for a user to interact with spark without having to remember any magic-specific syntax.
@aggFTW What do you think of this idea?

**Comment by aggFTW** [comment]
I like it! I was also thinking of specifying a language for a specific endpoint. So, for adding an endpoint, you would provide url, username, password and language. That will allow us to handle languages differently, which is needed for our integration with automatic visualization.

I'll start the change to take a language for an endpoint now. We can then merge our changes.

Thanks @alope107!
