### ISSUE TITLE
Drop Python 2

### ISSUE THREAD

**Issue by itamarst** [jupyter-incubator/sparkmagic#607]
1. Python 2 is no longer being maintained as of Jan 1, 2020.
2. The first PySpark release in 2020 will drop Python 2.

Users on Python 2 can continue to use old versions of Sparkmagic, but we should be strongly discouraging Python 2 usage.

Important: add metadata to `setup.py` to say "this only supports Python 3 or later", and then `pip` will automatically pick the right version of SparkMagic. Specifically `python_requires=">=3.5"` or something along those lines.

**Comment by devstein** [comment]
Closed by #689
