### ISSUE TITLE
Standard for accepting PRs

### ISSUE THREAD

**Issue by itamarst** [jupyter-incubator/sparkmagic#609]
@devstein @juhoautio @suhsteve (assuming you're not already getting notified of new issues?)

Here's my current checklist for accepting PRs, should probably add it to docs somewhere:

* Has unit tests for change.
* If it's adding feature, has examples in the example notebooks.
* Documented in README where relevant.
* Manual testing on notebook.

See also the https://github.com/jupyter-incubator/sparkmagic/milestone/7 milestone in general.

**Comment by devstein** [comment]
@itamarst Thoughts on adding this list as a PR template?

**Comment by itamarst** [comment]
Sounds good, go for it.
