### ISSUE TITLE
[BUG] Missing positional argument in RemoteSparkMagic 

### ISSUE THREAD

**Issue by LinanZheng** [jupyter-incubator/sparkmagic#627]
**Describe the bug**
SparkMagic will throw `TypeError: _print_endpoint_info() missing 1 required positional argument: **'current_session_id'` if the user uses subcommand `info` and provides URL. The issue can be easily traced back to line 125 in `remotesparkmagics.py`. I can help fix the issue but the challenge right now is what should be the expected behavior of this combination since that method signature is changed? I had a quick fix by enforcing both url and id arguments so that the method can be called properly but the rendered HTML output does not make a lot of sense.

**To Reproduce**
```
%load_ext sparkmagic.magics
%spark info -u http://spark:8998
```

**Versions:**
 - SparkMagic: Master

**Comment by itamarst** [comment]
Given it's informational, any sort of useful information would be fine, it doesn't have to exactly match what was there before. A PR would be great, thank you.

**Comment by LinanZheng** [comment]
@itamarst I have created a bugfix PR to address this issue. Thanks!

**Comment by LinanZheng** [comment]
@itamarst MR has been merged with passing CI. I will close the issue now. Thanks for the help!
