### ISSUE TITLE
Implement SIGINT callback to cancel Livy statements

### ISSUE THREAD

**Issue by LinanZheng** [jupyter-incubator/sparkmagic#629]
**Is your feature request related to a problem? Please describe.**
This feature request is a follow up to the PR https://github.com/jupyter-incubator/sparkmagic/pull/628. Once the MR is merged, users will be able to cancel statements but having the notebook automatically sending cancel request when the kernel receives SIGINT would be a great addition to the repo. 

**Describe the solution you'd like**
Implement a contextmanager function or other SIGINT handler to send cancel request when the user press the interrupt button in Jupyter Notebook. Cancellation logics has been implemented in the original PR linked above

**Additional context**
Follow up enhancement to PR https://github.com/jupyter-incubator/sparkmagic/pull/628

**Comment by hanyucui** [comment]
@PedroRossi @itamarst  This is very helpful. Any progress on this?

CC: @jigar-komodo
