### ISSUE TITLE
Installation is hard

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#63]
See title; installation is a few steps, which should ideally all be subsumed by a Pip install.

**Comment by aggFTW** [comment]
Installation currently requires:

1. Copy config file to ~/.sparkmagic/config.json
2. Install kernel specs manually.
3. pip install from local

Ideally, you could just `pip install remotesparkmagics` and 1 and 3 would be done.
As for 2, we would break the wrapper kernels into their own repo and have them be pip installable too.

**Comment by msftristew** [comment]
1 is partially resolved by #77. Now no config file is necessary to run the magics (but it's necessary to override any defaults). We can talk about next steps for this later but a lot of it comes down to how we choose to restructure the repository.

2 is not solved but it's made easier with #98. What remains is putting together the pip command to perform the installation automatically (how do we do this?)

**Comment by aggFTW** [comment]
By closing #58 and submitting project to PyPl, we'd tackle the rest of this.
