### ISSUE TITLE
Configure livy session start up time

### ISSUE THREAD

**Issue by devender-yadav** [jupyter-incubator/sparkmagic#630]
I need to pass few jars while creating spark session.

Configure command used:

```
%%configure -f
{
 "name": "test-xgboost",
 "conf":{
    "spark.jars.packages": "ml.dmlc:xgboost4j-spark:0.90,com.esotericsoftware.reflectasm:reflectasm:1.08"
     
    }
}
```
This is taking more than 60 seconds but current session timeout is 60 seconds.

```
The code failed because of a fatal error:
	Session 4 did not start up in 60 seconds..
```

How can I configure livy session start up time?

**Comment by LinanZheng** [comment]
You can override this config programmatically like this:
```
import sparkmagic.utils.configuration as conf
conf.override("livy_session_startup_timeout_seconds", 1000)
```

**Comment by devstein** [comment]
@LinanZheng  is correct. Also, checkout the [example config](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/example_config.json#L46)
