### ISSUE TITLE
[BUG] Build docker compose error using master branch

### ISSUE THREAD

**Issue by c3f8** [jupyter-incubator/sparkmagic#631]
**Describe the bug**
Trying to build the images of the master branch.
Getting the error 

`/apps/build/spark/build/mvn: line 159:   972 Killed                  "${MVN_BIN}" -DzincPort=${ZINC_PORT} "$@"`

Using docker on windows 10.

**To Reproduce**
Clone the master branch. 
Exec docker-compose build.

**Comment by itamarst** [comment]
You might have run out of memory? Try adding more memory to the VM running Docker.

**Comment by c3f8** [comment]
Hi there,

Thanks for the tip. It worked on a 5GB memory docker. It used to be 4GB.
