### ISSUE TITLE
Way to move data from spark to local?

### ISSUE THREAD

**Issue by sid-kap** [jupyter-incubator/sparkmagic#634]
Would it be possible to move data (like a pandas dataframe or pyspark dataframe) from the spark cluster to the local env? i.e. similar to `%%send_to_spark`, except in the opposite direction?

**Comment by itamarst** [comment]
This is possible, yes, in newer versions; it's documented in one of the example notebooks. If you can't find it I'll try to track it down tomorrow.

**Comment by sid-kap** [comment]
Can you look this up for me? I wasn't able to find it in the notebooks

**Comment by yegeniy** [comment]
Use the `%%spark -o var_name` flag. 

https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Magics%20in%20IPython%20Kernel.ipynb

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/292802/75212039-b2176080-5753-11ea-8780-99cad23247a7.png">

**Comment by sid-kap** [comment]
Ah ok. I knew about this, but I was hoping there would be a faster way that didn't require a SQL query, and didn't require multiple steps. (I think this also requires first doing `people_spark_df.createOrReplaceTempView('people')` before the cell 5 that you showed.)

**Comment by yegeniy** [comment]
Ah, as far as I know, the sql part is optional. Just omit the `sql` Part
and treat it like any `%%spark` cell. My experience was using this in EMR,
where the version of sparkmagic is slightly different though. I would be
surprised if it wasn’t possible. If it doesn’t work for you, try pasting a
minimal example here.

**Comment by sid-kap** [comment]
@yegeniy It's not the `-c sql` part that I'm complaining about, it's the `SELECT * FROM people` that I think should be unnecessary. I wish there was some way to do this that didn't require two commands, and at least one cell for every table I want to copy over:

```
[1]
df_1.createOrReplaceTempView('df_1')
df_2.createOrReplaceTempView('df_2')
...

[2]
%% spark -o df_1
SELECT * FROM df_1

[3]
%% spark -o df_2
SELECT * FROM df_2

...
```

**Comment by yegeniy** [comment]
@sid-kap does the following work?

```
%%spark -o df
df = spark.read.parquet(...)
```

**Comment by yegeniy** [comment]
@sid-kap that seems to work. Here's an example I just tried in a local Python3 kernel that's using sparkmagic:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/292802/75405197-e9644980-58da-11ea-81ff-58f0db190d42.png">

**Comment by sid-kap** [comment]
Awesome, I will try that. Thanks!
