### ISSUE TITLE
[BUG]python version >=3.8.0 cannot jupyter install pysparkkerrnel

### ISSUE THREAD

**Issue by zesluo** [jupyter-incubator/sparkmagic#636]
**Describe the bug**

Hello! I'm doing a vscode extension tool. I just found that python version >=3.8.0 cannot jupyter install pysparkkerrnel. However, it can work if python <3.8.0. our tool use ‘jupyter install sparkmagic’ and ‘jupyter.exe kernelspec install pysparkkernel’. As the picture shown, the link is here: https://pypi.org/project/sparkmagic/0.15.0/#history, it doesn’t apply to python 3.8.0.  Do we have any plan to include python 3.8 in the near future or any method to workaround? Thanks a lot!

![image](https://user-images.githubusercontent.com/46309533/77922304-7718c780-72d3-11ea-986a-d26f053d4363.png)

![image](https://user-images.githubusercontent.com/46309533/77922590-d37be700-72d3-11ea-852e-13d38e286396.png)
![image](https://user-images.githubusercontent.com/46309533/77922612-d8d93180-72d3-11ea-93ae-9f75d152e3b5.png)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Versions:**
 - SparkMagic
 - Livy (if you know it)
 - Spark

**Additional context**

**Comment by devstein** [comment]
@zesluo To my knowledge, we plan on supporting Python >= 3.8.0. I'll prioritize when I can. If you know how to fix, feel free to make a PR and I'll review!

**Comment by zesluo** [comment]
Hello @devstein ,

Thanks for your reply and sharing the knowledge! It would be very wonderful if you can prioritize it. We are looking forward to it. Thanks a lot! ^_^

**Comment by PedroRossi** [comment]
Hi @zesluo this bug is related to the IPython package, try to update IPython to at least 7.13 that it should work (or break something since this is a huge update from 4.x to 7.13). For more info this issue describes the bug https://github.com/ipython/ipython/issues/11375

**Comment by zesluo** [comment]
@PedroRossi Thanks for your reply. We are currently using sparkmagic 0.12.8 since we need both pysparkkernel and pyspark3kernel . After I try to upgrade IPython, it shows me error like this as follows. Could you help adjust the restriction so we can use it? Thanks  
![image](https://user-images.githubusercontent.com/46309533/79133302-604b9800-7dde-11ea-8cfc-7b3d607ea637.png)

**Comment by PedroRossi** [comment]
@zesluo upgrade sparkmagic to 0.12.9

**Comment by zesluo** [comment]
@PedroRossi if we upgrade to 0.12.9, we will not have both pysparkkernel and pyspark3kernel at the same time. >_<

**Comment by PedroRossi** [comment]
@zesluo have you tested running with 0.12.9 to see if there is any issues with it? if so send the logs so I can have look at what is the problem. As a last resort just editing the sparkmagic requirements should work

**Comment by itamarst** [comment]
You don't need pysparkkernel / pyspark3kernel to use python 2 and 3. In modern Livy it's a thing you have to change on Livy side, you just use the same kernel on the client side.

**Comment by itamarst** [comment]
That is, newer versions of sparkmagic still support both Python 2 and Python 3.

**Comment by zesluo** [comment]
@itamarst Thanks for your reply!. I just downloaded the latest version of sparkmagic. Do you mean that I only need 'pysparkkernel' as the pic shown to support both Python 2 and Python 3?
![image](https://user-images.githubusercontent.com/46309533/79234476-e4fceb80-7e9c-11ea-8e8c-e192da6e2110.png)

**Comment by itamarst** [comment]
Correct. You need to configure Python 2 vs 3 on the Livy side. As per the docs for Livy, `To change the Python executable the session uses, Livy reads the path from environment variable PYSPARK_PYTHON (Same as pyspark).`

**Comment by itamarst** [comment]
(Also, you really shouldn't use Python 2 for new code, it's end-of-lifed...)
