### ISSUE TITLE
Running Spark Kernel with Papermill?

### ISSUE THREAD

**Issue by gthomas-slack** [jupyter-incubator/sparkmagic#637]
Is it possible to run the Spark kernel with https://github.com/nteract/papermill or is the standard iPython Kernel only supported currently?

I have a notebook using the Spark Kernel setup which looks like this
![image](https://user-images.githubusercontent.com/45470716/78944698-51c64f00-7a73-11ea-8291-50c2aa72587a.png)

If I attempt to run this through papermill, the following error is received:
```
  File "/.venv/lib/python3.8/site-packages/papermill/translators.py", line 24, in find_translator
    raise PapermillException(
papermill.exceptions.PapermillException: No parameter translator functions specified for kernel 'sparkkernel' or language ''
```

Thank you for looking!

**Versions:**
 - papermill==2.1.0
 - sparkmagic==0.15.0
 - Python 3.8

**Comment by devstein** [comment]
Hi @gthomas-slack 

The PySpark and Spark kernel isn't natively supported by `papermill` but its an easy fix! Checkout [our fork](https://github.com/viaduct-ai/papermill/commit/7ade4f846f9984834968a5aead6901b09bf5c695#diff-224686b95650089fdb431a157197f300R280)  for an example.  We added support for the PySpark kernel, but adding support for the Spark kernel would be as simple as adding this line
```python
papermill_translators.register("sparkkernel", ScalaTranslator)
```

**Comment by gthomas-slack** [comment]
@devstein Thankyou so much for your quick reply - I'll take a look at your fork! :)

**Comment by gthomas-slack** [comment]
Hi @devstein Thanks again for your help here. I've started using your fork, and it's working well.

One question for you - have you been able to get papermill injected parameters working with the `%%sql` magic?

Basically looking to do something like this image, where `{ds}` would be replaced with the variable from the `pySpark` session. Seems like this should be possible, but I could not find any examples or documentation. 

![image](https://user-images.githubusercontent.com/45470716/82952085-33ea7600-9f5d-11ea-886c-b9553c3b07bd.png)

**Comment by devstein** [comment]
Hi @gthomas-slack, unfortunately, this is not possible with the current implementation of the `%%sql` magic. See the [implementation here](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/sqlquery.py#L29).  It would be a great feature to add. 

The workaround is to use `spark.sql` instead. For example

```python
# injected parameters
ds='2020-01-01`

print(ds)

query = f"select * from dw.dim_date where full_date='{ds}' limit 10"
df = spark.sql(query)

df.show()
```

**Comment by gthomas-slack** [comment]
Thanks @devstein ! If I find some time I may look into adding this feature :)
