### ISSUE TITLE
Support for passwords per notebook

### ISSUE THREAD

**Issue by PedroRossi** [jupyter-incubator/sparkmagic#638]
**Is your feature request related to a problem? Please describe.**
In the current setup at my company we use Jupyterhub to deliver Jupyter Notebooks to scientists across the company and we authenticate using Kerberos, but given some internal refactors in progress we are planning on using LDAP to authenticate, but we don't want to store the plain password on the config file since we don't want to save it on the storage disk (we only mount the home folder, the rest is ephemeral)

**Describe the solution you'd like**
It would be good to have a magic to set the current user/password to use or maybe read these credentials from somewhere else

**Comment by PedroRossi** [comment]
@itamarst @devstein @LinanZheng if you could take a look at this later for opinions it would be great!

**Comment by devstein** [comment]
@PedroRossi Would it make sense to read the user/pass from customizable environment variables?

**Comment by PedroRossi** [comment]
@devstein yes! I am going to research a little more and keep this issue updated

**Comment by PedroRossi** [comment]
I ended up not needing to support this actually, if someone else needs this kind of support we can discuss this matter again, going to close this issue for now.
