### ISSUE TITLE
Rethink configuration

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#64]
This is part of a greater architectural issue around configurations. There should be a configuration module which:
1. Automatically loads data from a configuration file,
2. loads the configuration with an appropriate set of defaults if things are missing from the configuration file, and
3. allows a developer to substitute a different configuration module if necessary (i.e. for tests).

**Comment by aggFTW** [comment]
Goals:

1. break configuration settings into different files per project
2. have defaults in centralized place
3. have get_config method return defaults from the centralized place
4. be able to easily unit test without config files
5. allow config changes at runtime for unit testing purposes

**Comment by msftristew** [comment]
PR #77
