### ISSUE TITLE
[BUG] send_to_spark does not reuse the existing Livy session

### ISSUE THREAD

**Issue by hanyucui** [jupyter-incubator/sparkmagic#641]
**Describe the bug**
Not sure whether this is expected or a bug. Using the PySpark kernel, when I call `send_to_spark` to send a local variable to Spark, it creates a new session and sends the variable to the new session. However later code still uses the older session and hence cannot access the variable I sent.

**To Reproduce**
```pyspark
%load_ext sparkmagic.magics
%manage_spark
```

```pyspark
sc.applicationId
```

```pyspark
%%local
s = "local"
```

```pyspark
%%send_to_spark -i s
```

```pyspark
sc.applicationId
```

```pyspark
s
```

**Expected behavior**
I would expect `send_to_spark` to use an existing session rather than creating a new one. I am also fine if all code uses the newly created session after `send_to_spark` executes, although it's not perfect.

**Screenshots**
The attached screenshots show the output of the code above:
<img width="879" alt="Screen Shot 2020-04-20 at 5 01 41 PM" src="https://user-images.githubusercontent.com/9649417/79811237-160c6e80-832a-11ea-94c8-568f5c51ee02.png">
<img width="926" alt="Screen Shot 2020-04-20 at 5 01 57 PM" src="https://user-images.githubusercontent.com/9649417/79811242-1a388c00-832a-11ea-9692-b39c13015227.png">

**Versions:**
 - SparkMagic: 0.15.0
 - Livy (if you know it):  0.6.0
 - Spark: 2.4.4

CC: @jigar-komodo

**Comment by PedroRossi** [comment]
This is indeed a BUG, the function [do_send_to_spark](https://github.com/jupyter-incubator/sparkmagic/blob/ea9244f9759cbddc7b944fd4757cf088be5a5261/sparkmagic/sparkmagic/magics/sparkmagicsbase.py#L51) is called by the `send_to_spark` magic and has a session_name variable to its args but it does not use it anywhere.
Feel free to send a PR for this issue and ask for any help regarding this problem.

**Comment by hanyucui** [comment]
@PedroRossi I debugged it a little bit. It seems when I call `%manage_spark` to create a session, `RemoteSparkMagics` is used, and `KerneMagics.session_started` is not set, and hence the kernel magics have no idea a session has been created. Now, if I just execute any Python command, e.g., `import os`, to create a session, `KerneMagics.spark()` is called, and `KerneMagics.session_started` is properly set. I am not quite sure how to keep both parties on the same page.

**Comment by hanyucui** [comment]
Hi @PedroRossi, I took another look. Are `RemoteSparkMagics` and `KernelMagics` no interoperable by design? Otherwise it doesn't explain why both classes implement the `%%spark` magic. Both are pretty helpful for me and it's hard to choose one over the other.

**Comment by PedroRossi** [comment]
Hi @hanyucui! Sorry for the delay, I had some time off work so I was off from github as well. It is just as you said, both classes implement %%spark but they aren't interoperable since the KernelMagics is the base for the kernels and the RemoteSparkMagics is the magic only to invoke through the python kernel.

In our case you are trying to load the RemoteSparkMagics while on the scala kernel? If this is case it shouldn't work since this wasn't the usage expected

**Comment by hanyucui** [comment]
I was trying to using RemoteSparkMagics while on the PySpark kernel. However, I was still using KernelMagics. It seems this shouldn't work either by looking at the code. I will close this issue.

**Comment by SimoneRichetti** [comment]
Hi guys! I'm encountering the same issue of @hanyucui about `%%send_to_spark` creating a new Spark session instead of connecting to the existing one. Any solution to that? I really didn't get the KernelMagics / RemoteSparkMagics issue, I'm not very practical about Jupyter and IPython.

**Comment by hanyucui** [comment]
> Hi guys! I'm encountering the same issue of @hanyucui about `%%send_to_spark` creating a new Spark session instead of connecting to the existing one. Any solution to that? I really didn't get the KernelMagics / RemoteSparkMagics issue, I'm not very practical about Jupyter and IPython.

My suggestion is don’t use RemoteSparkMagics — not worth the trouble.

**Comment by SimoneRichetti** [comment]
> My suggestion is don’t use RemoteSparkMagics — not worth the trouble.

Concretely, what does this implies? Do I have to change some settings or configurations? What are `KernelMagics` and `RemoteSparkMagics`?

**Comment by durgaswaroop** [comment]
Hello. I have the same issue. Doesn't looks like this has been resolved. Can this be opened again? And meanwhile, is there a temporary fix?
