### ISSUE TITLE
%%spark config doesn't recognize official key name like "spark.driver.memory" 

### ISSUE THREAD

**Issue by eromoe** [jupyter-incubator/sparkmagic#645]
Hi，

I have checked help，
```
%spark ?
config
    Override the livy session properties sent to Livy on session creation. All session creations will
    contain these config settings from then on.
    Expected value is a JSON key-value string to be sent as part of the Request Body for the POST /sessions
    endpoint in Livy.
    e.g. `%%spark config`
         `{"driverMemory":"1000M", "executorCores":4}`
```

It only support  config like `{"driverMemory":"1000M", "executorCores":4}`  . 

But refer to spark document 
https://spark.apache.org/docs/latest/configuration.html

![image](https://user-images.githubusercontent.com/3938751/81535876-28178500-939d-11ea-95bd-c6777a7f601c.png)

I think offical config should be support too .

Here I have a spark config, 
"spark.driver.memory" -> "driverMemory" is clear .
"spark.driver.maxResultSize" -> "driverMaxResultSize" failed .
How to convert `spark.sql.session.timeZone` ?  

```
%%spark config
{ 
    "spark.driver.memory": "5g",
    "spark.driver.maxResultSize": "5g",
    "spark.executor.memory": "4g",
    "spark.executor.memoryOverhead": "2g",
    "spark.kryoserializer.buffer.max": 1024,
    "spark.executor.instances": 6,
    "spark.executor.cores": 3,
    "spark.sql.session.timeZone":"Asia/Shanghai" 
}
```

**Comment by eromoe** [comment]
Seems sparkmagic only support 15 config , why ?

**Comment by devstein** [comment]
@eromoe `sparkmagic` uses [Apache Livy](https://livy.incubator.apache.org/docs/latest/rest-api.html#post-sessions) to control spark sessions. This configurations is an artifact of the [Livy Post Sessions API](https://livy.incubator.apache.org/docs/latest/rest-api.html#post-sessions), so we cannot change this.
