### ISSUE TITLE
[BUG] getting all sessions raises an exception if kind not supported

### ISSUE THREAD

**Issue by mmigdiso** [jupyter-incubator/sparkmagic#647]
**Describe the bug**
When there is an session with a kind that doesn't exist in constants.LIVY_KIND_PARAM, %load_ext sparkmagic.magics raises _BadUserDataException: Session of kind 'sql' not supported. Session must be of kinds spark, pyspark, sparkr._

**To Reproduce**
1- Create an interactive sql session on livy 
wget --no-check-certificate --quiet \
  --method POST \
  --timeout=0 \
  --header 'Content-Type: application/json' \
  --body-data '{"kind": "sql"}' \
   'http://localhost:8998/sessions'
2- restart Jupyter
3- jupyter fails with _**BadUserDataException: Session of kind 'sql' not supported. Session must be of kinds spark, pyspark, sparkr.**_

**Expected behavior**
sparkmagic should ignore the types that are not supported, It is not always possible to clean/kill sessions on livy

**Screenshots**

**Versions:**
 - SparkMagic 0.15.0
 - Livy "0.7.0-incubating"
 - Spark 2.4.5

**Additional context**
See the attachment for a stack trace
[jupyter_bug_stacktrace.txt](https://github.com/jupyter-incubator/sparkmagic/files/4660418/jupyter_bug_stacktrace.txt)

**Comment by devstein** [comment]
Closed by #648

**Comment by achidlow** [comment]
Is it possible to push a new release to PyPI with the fix from #648 please? This issue is still occurring in the latest release which was before that PR was merged :)

**Comment by itamarst** [comment]
I'll see if I can do that today.

**Comment by itamarst** [comment]
Done; 0.16.0 should have the fix.

**Comment by achidlow** [comment]
Legend, thank you!
