### ISSUE TITLE
Add pluggable authentication support

### ISSUE THREAD

**Issue by alexismacaskilll** [jupyter-incubator/sparkmagic#659]
SparkMagic supports remote access to Hadoop clusters from Jupyter notebooks, but does not support Google authentication unless customers open their Virtual Private Cloud (VPC) networks to outside connections, which poses an untenable security risk. Due to this risk, customers cannot safely use SparkMagic from outside their project. We want to allow users to be able to dynamically connect to an existing Google Dataproc cluster with Livy installed from a remote Jupyter notebook with Google authentication.

In order to add Google Authentication to SparkMagic, it requires that we add a lot of changes that are google specific. So instead of hard-coding in all of these google specific changes, it would be cleaner to allow custom authentication classes. After sparkmagic can support pluggable auth, we can put our Google authentication support in a lightweight wrapper project that has Sparkmagic as a dependency. 

We have considered hardcoding in Google authentication similar to how Sparkmagic hard codes in Kerberos Authentication; however, we want this to be maintainable and adding support for pluggable auth seems to be a better way to ensure that.

**Comment by max-sixty** [comment]
Does sparkmagic support dataproc?
