### ISSUE TITLE
[BUG] Sometimes, a jupyter cell will end with : Error sending http request and maximum retry encountered

### ISSUE THREAD

**Issue by BertrandBrelier** [jupyter-incubator/sparkmagic#665]
**Describe the bug**
I am running a Spark cluster on EMR AWS and run from a local jupyter notebook using anaconda Anaconda3-2020.07-Linux-x86_64 . I setup the ssh tunnel and can start and run a spark code. Once in a while, a cell will terminate with the error:

Error sending http request and maximum retry encountered.

I looked if someone else posted the same question. In my case, most of my jupyter cells are correctly executed on the Spark cluster. The difference is that it is not systematic for me, I have this issue once in a while . 

Are there any options to tune to increase the number of retry ?

Thank you for your help,

**To Reproduce**
Not sure how to reproduce this issue

**Expected behavior**
I expected the cell to run.

**Screenshots**

**Versions:**
 - SparkMagic :  0.15.0
 - Livy (if you know it) : 0.7.0
 - Spark : 2.4.5

**Additional context**

**Comment by devstein** [comment]
@BertrandBrelier Thanks for making an issue. We have support for configuring the max retries and the delay between retries. You can find the relevant configuration [here](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/utils/configuration.py#L232-L246). These configuration functions map to keys in your Sparkmagic configuration JSON or can be set via code.

Hope this helps!

**Comment by BertrandBrelier** [comment]
Hello @devstein ,
Thank you for your help. 
I am not sure to understand which parameters to modify in the .sparkmagic/config.json file.

Right now, I have the following options:

"wait_for_idle_timeout_seconds": 15,
  "livy_session_startup_timeout_seconds": 60,

  "heartbeat_refresh_seconds": 30,
  "livy_server_heartbeat_timeout_seconds": 0,
  "heartbeat_retry_seconds": 10,

  "retry_policy": "configurable",
  "retry_seconds_to_sleep_list": [0.2, 0.5, 1, 3, 5],
  "configurable_retry_policy_max_retries": 8

Do you advise a different set of values for these options or are there other options I should use to run cells taking longer using Spark Magic ?

I realized that I am experiencing the "Error sending http request and maximum retry encountered" issue only for cells taking some time to execute. The fast cells never experience this issue.

Thank you for your help,

Cheers,

Bertrand
