### ISSUE TITLE
[BUG] Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/conda/man/man1/nosetests.1'

### ISSUE THREAD

**Issue by nickwallen** [jupyter-incubator/sparkmagic#669]
**Describe the bug**
I am unable to spin-up the Docker Compose based development environment. This fails with the following error message.
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/conda/man/man1/nosetests.1'
Consider using the `--user` option or check the permissions.

ERROR: Service 'jupyter' failed to build : The command '/bin/sh -c if [ "$dev_mode" = "true" ]; then       
cd hdijupyterutils && pip install . && cd ../ &&       cd autovizwidget && pip install . && cd ../ &&       
cd sparkmagic && pip install . && cd ../ ;     else pip install sparkmagic ; fi' returned a non-zero code: 1
```

**To Reproduce**
Run the following in the project's root directory.
```
docker-compose build
```

Or more directly, you can execute the following in the project's root directory.
```
docker build . -f ./Dockerfile.jupyter -t jupyter/sparkmagic
```

**Expected behavior**
I expected to be able to access the Jupyter notebook in my browser at http://localhost:8888 (as described in the README.)

**Screenshots**
none

**Versions:**
 - SparkMagic: 0.16.0 
 - Livy (if you know it) 0.6.0-incubating
 - Spark 2.3.3

**Additional context**
none

**Comment by nickwallen** [comment]
It has something to do with the specific version of `jupyter/base-network` that is being used.  I made the following change in Dockerfile.jupyter and it works as expected.
```
#FROM jupyter/base-notebook:ae885c0a6226
FROM jupyter/base-notebook
```

**Comment by devstein** [comment]
@nickwallen Thanks for finding! As `sparkmagic` supports the latest Jupyter I will unpin the jupyer/base-notebook image
