### ISSUE TITLE
[BUG] url is not passed from config.json file

### ISSUE THREAD

**Issue by gthomas-slack** [jupyter-incubator/sparkmagic#683]
**Describe the bug**
I am using `sparkmagic` with a custom Authentication class but am running into the following error message when attempting to run any magic command:

```
The code failed because of a fatal error:
	Failed to change language to python.
Exception details:
	"'Namespace' object has no attribute 'url'".

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.
```

I am able to fix the bug by making the change in this branch: https://github.com/jupyter-incubator/sparkmagic/compare/master...gthomas-slack:gthomas-fix-url-passing

However I am unsure if that is the correct fix, or if I'm doing something else wrong, would love any guidance here

Happy to provide more detail on the issue if we determine this is not the correct fix

**Versions:**
 - SparkMagic==0.17.0
 - Livy 
 - Spark==2.4.5

**Comment by gthomas-slack** [comment]
https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/auth/customauth.py#L20 Here is where it tries to read the `url` attribute from the Namespace object.

cc @alexismacaskilll since it looks like you added the awesome custom authentication logic, and will likely have context on this :) 

Thanks!

**Comment by alexismacaskilll** [comment]
> https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/auth/customauth.py#L20 Here is where it tries to read the `url` attribute from the Namespace object.
> 
> cc @alexismacaskilll since it looks like you added the awesome custom authentication logic, and will likely have context on this :)
> 
> Thanks!

This looks like the correct fix to me!

**Comment by rathboma** [comment]
We're seeing this when using SparkMagic 0.17. How easy would it be to add a patch release with the fix?

**Comment by gthomas-slack** [comment]
Raised a PR with the fix https://github.com/jupyter-incubator/sparkmagic/pull/684

Would be great if we could get a patch release out with the fix, thanks!
