### ISSUE TITLE
[BUG] Avoid using `{ }` for code block with broken code lines

### ISSUE THREAD

**Issue by pancodia** [jupyter-incubator/sparkmagic#687]
**Describe the bug**

I am using Sparkmagic's Spark kernel (Scala) provided by AWS SageMaker notebook instance. I find if I need to break a long code line to multiple lines, I had to enclose them in a pair of curly braces (even though I have `.` in front of each broken code lines) so that the notebook will recognize them as a single code block. Is it possible to allow a cell to executed a code block with broken lines without requiring using curly braces.

For example, right now I have to use the following code to make it work:

```
{
myDataFrame.write
    .format("csv")
    .options(Map("header"->"true", "sep"->","))
    .mode(SaveMode.Overwrite)
    .save("/path/to/save/data")
}
```

Ideally, I would like to not have to use curly braces.

**To Reproduce**

See the example provided in the description.

**Expected behavior**

See the example provided in the description.

**Screenshots**

N/A

**Versions:**
 - SparkMagic 0.16.0
 - Livy (if you know it) 0.7.0-inc
 - Spark 2.4

**Additional context**

AWS EMR version 5.30.0

**Comment by devstein** [comment]
@pancodia You can use `\` to break lines

```
myDataFrame.write \
    .format("csv") \
    .options(Map("header"->"true", "sep"->",")) \
    .mode(SaveMode.Overwrite) \
    .save("/path/to/save/data")

```

**Comment by pancodia** [comment]
Thanks. Does it also work for Scala?

**Comment by devstein** [comment]
@pancodia with Scala Spark kernel I don't need `\`. I am not using SageMaker, but the following code works for me in my local environment

```scala
myDataFrame.write.
    format("csv").
    options(Map("header"->"true", "sep"->",")).
    mode(SaveMode.Overwrite).
    save("/path/to/save/data")
```
