### ISSUE TITLE
Support LSP by completing the kernel metadata

### ISSUE THREAD

**Issue by krassowski** [jupyter-incubator/sparkmagic#691]
As reported in https://github.com/krassowski/jupyterlab-lsp/issues/407, [jupyterlab-lsp](https://github.com/krassowski/jupyterlab) (an extension that integrates fancy IDE features with JupyterLab) does not work with spark magic unless manual modifications are made to the kernel, this is adding `file_extension` in `language_info` and changing `language` in [sparkkernel.py](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/kernels/sparkkernel/sparkkernel.py) so that it looks closer to:

```python
class SparkKernel(SparkKernelBase):
    def __init__(self, **kwargs):
        implementation = 'Spark'
        implementation_version = '1.0'
        language = 'scala'    # or LANG_SCALA ?
        language_version = '0.1'
        language_info = {
            'name': 'scala',
            'mimetype': 'text/x-scala',
            'codemirror_mode': 'text/x-scala',
            'file_extension': '.sc',
            'pygments_lexer': 'scala'
        }

        session_language = LANG_SCALA


```

This is required for the LSP integration using jupyterlab-lsp. We received a [PR instructing user to manually patch sparkmagic](  https://github.com/krassowski/jupyterlab-lsp/pull/415), but we think that it would be ideally addressed here, if it would not be a problem. I do not understand enough about sparkmagic to know why language is set to `'no-op'`, nor if it can be changed to declare the actual language in the standard attribute rather than in the non-standard `session_language` - I would appreciate some feedback here!

**Comment by krassowski** [comment]
I am happy to open a PR, if changing `'no-op'` is an option.

**Comment by devstein** [comment]
@krassowski Thanks for making a detailed issue! I agree we should fix this within `sparkmagic` itself. Can you verify this [PR](https://github.com/jupyter-incubator/sparkmagic/pull/692/files) will resolve this issue?
