### ISSUE TITLE
A magic token to start a default pySpark session based on the config values.

### ISSUE THREAD

**Issue by eyal-lantzman** [jupyter-incubator/sparkmagic#697]
**Is your feature request related to a problem? Please describe.**
It's annoying that i need to %manage_spark and then click on connect. Is there a way to do that for python kernel (at least) with the default options? I don't mind passing in the session name, something like %default_pyspark_connect my_session_name

**Describe the solution you'd like**
I want a new magic word that would allow me to establish a livy session based on config values. %default_pyspark_connect 

**Describe alternatives you've considered**
Could not find any.

**Additional context**
None

**Comment by eyal-lantzman** [comment]
Found a existing solution, closing:
%spark add -s test -l python -u https://sparkcluster.net/livy -t Kerberos -a u -p -k

**Comment by devstein** [comment]
@eyal-lantzman Thanks for closing and posting the solution for future viewers!
