### ISSUE TITLE
Release 0.18.0 on pypi

### ISSUE THREAD

**Issue by gthomas-slack** [jupyter-incubator/sparkmagic#699]
Hi, I see that sparkmagic 0.18.0 was released on January 2nd: https://github.com/jupyter-incubator/sparkmagic/releases

However it's not currently released to pypi, where the latest version is still currently 0.17.1. Would it be possible to get the release pushed to pypi? Thanks!

**Comment by devstein** [comment]
@gthomas-slack Thanks for pointing this out! This was not intentional. @itamarst Any suggestions here?

**Comment by itamarst** [comment]
Probably some sort of problem in the release process? Possibly it only runs on tags on the `release` branch, see `.travis-ci.yml`. Should really be switched to GitHub Actions, although that means getting someone with PyPI access to give you access so you get a secret token... I don't have it :)

**Comment by devstein** [comment]
Found the issue. The release was configured for the [only Python 2 CI](https://github.com/jupyter-incubator/sparkmagic/blob/master/.travis.yml#L30-L42), which has been removed. I will fix it. 

@itamarst Who has PyPi access? I can move us to GitHub actions if we can get a secret token

**Comment by itamarst** [comment]
See https://pypi.org/project/sparkmagic/ Maintainers list, on left hand side. I would ask for PyPI access for yourself, given you're doing most of the maintenance, and it's easier if you have access and don't rely on others.

**Comment by devstein** [comment]
@gthomas-slack Fixed https://pypi.org/project/sparkmagic/

**Comment by gthomas-slack** [comment]
Thanks for the quick fix!
