### ISSUE TITLE
[QUESTION] How to switch Livy Endpoint when using PySpark Kernel?

### ISSUE THREAD

**Issue by rathboma** [jupyter-incubator/sparkmagic#702]
Hey folks,

Firstly -- LOVE this project. Using it heavily. Thank you for making it :-).

If I'm using an `ipython` kernel I can create a custom livy session using `spark add`:

```
%spark add -s mysession -l python -t Kerberos -u http://livy.example.com`
```
This is great! I can maintain several sessions.

## PySpark Kernel - Livy Endpoints hard-coded in the config file?

However my understanding is that for the `pyspark` and `spark` kernels the session configuration is done via `~/.sparkmagic/config.json`, so the endpoints are hard-coded.

Is that understanding correct? Or is there a way to add & delete sessions in pyspark kernels?

**Comment by rathboma** [comment]
Hey folks, following up to see if there's an answer to this?

Again, thanks for all your work!

**Comment by devstein** [comment]
Hi @rathboma glad you enjoy using sparkmagic and thanks for making an issue! 

You can also use 

```
%load_ext sparkmagic.magics
```
```
%spark add -s mysession -l python -t Kerberos -u http://livy.example.com`
```
**before your first code cell** in a `pyspark` or `spark` kernel to configure the livy endpoint for the kernel. 

For deleting sessions, you can use always use the `%%delete` magic to delete a specific session.

I don't think you can maintain multiple session at once in the same kernel from `pyspark` or `spark`, but you could use `%spark add` and `%%configure` to use different kernels at different points in the notebook (i.e first 10 cells use Livy A, then you kill the session and start a new session with Livy B for the next 10 cells).

Hopes this helps and let me know if you have any more questions

**Comment by rathboma** [comment]
Hey! Ok so sounds like doing that overrides whatever is set in config.json?
