### ISSUE TITLE
Docker image in hub

### ISSUE THREAD

**Issue by ggittu** [jupyter-incubator/sparkmagic#703]
We are planning to make use of the spark magic, within our Jupiter hub. Now we use all-spark-notebook image what I got from the docker. and give this in the settings

c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.image = 'jupyter/all-spark-notebook'

Is there a similar image that we can use to make use of the spark magic ?

**Comment by devstein** [comment]
Hi, @ggittu thanks for making an issue! We have an [Dockerfile](https://github.com/jupyter-incubator/sparkmagic/blob/0.18.0/Dockerfile.jupyter) that you can use to build your own image, or use as a reference of how to install Sparkmagic in another image like `jupyter/all-spark-notebook`. We do not have a public Docker image that I can point you to, but someone else in the community may have made published one. 

Hopes this helps!
