### ISSUE TITLE
examples/Pyspark Kernel notebook does not render 

### ISSUE THREAD

**Issue by clayms** [jupyter-incubator/sparkmagic#707]
examples/Pyspark Kernel notebook does not render in GitHub page.

https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Pyspark%20Kernel.ipynb

No matter how many times I reload or which browser I use, I only see:

![image](https://user-images.githubusercontent.com/12793783/113475602-b462e880-9444-11eb-87fd-4e611636d6ad.png)

**Comment by Sharad24** [comment]
Does not open on https://nbviewer.jupyter.org/ either

**Comment by lopes-andre** [comment]
Same issue here.
