### ISSUE TITLE
UsageError: Cell magic `%%local` not found.

### ISSUE THREAD

**Issue by durgaswaroop** [jupyter-incubator/sparkmagic#712]
**Describe the bug**
I have installed spark magic and have done the necessary prerequisites as described in the README. I can use `%%spark`, `%manage_spark` but not `%%local`. It gives me the following error:
```
UsageError: Cell magic `%%local` not found.
```

**To Reproduce**
Install sparkmagic, run the prerequisite commands and then run a cell with `%%local` in it. 

**Expected behavior**
I am trying to follow this tutorial https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Send%20local%20data%20to%20Spark.ipynb and it is supposed to run the code but I am instead getting an error. 

**Versions:**
 - SparkMagic - 0.18.0
 - Livy - 0.7.1-incubating
 - Spark - 2.4.8
 - 
Let me know if I am missing any other libraries or extensions necessary.

**Comment by durgaswaroop** [comment]
Hello? Can someone help with this?

**Comment by devstein** [comment]
Hi @durgaswaroop are you using a `PySpark` kernel? The tutorial you shared uses a `PySpark` kernel.  `%%local` only works in Spark kernel, not a Pyhon3 kernel. You can always find out what magics are available with `%lsmagic`

**Comment by durgaswaroop** [comment]
Hi @devstein , I'm using a python kernel in the jupyter notebook if that's what you're asking. If `%%local` is not supported in `pyspark`, how can I send local files to Spark cluster with pyspark?

**Comment by devstein** [comment]
> how can I send local files/data to Spark cluster with pyspark?

You can follow [the tutorial](https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Send%20local%20data%20to%20Spark.ipynb) using a `PySpark` kernel not a regular Python kernel

**Comment by durgaswaroop** [comment]
@devstein I don't think I know what "psypark kernel" you're referring to. How can I verify that? What do I need to install/setup for that?

**Comment by devstein** [comment]
@durgaswaroop Follow the [installation instructions](https://github.com/jupyter-incubator/sparkmagic#installation)

**Comment by durgaswaroop** [comment]
@devstein, Yeah, I have done that. I am able to submit jobs with `%%spark` magic.  I just am not able to use the `%%local%% and `%%send_to_spark` magic commands. 

After installing spark magic, I ran this command mentioned in the instructions:
```
 jupyter nbextension enable --py --sys-prefix widgetsnbextension 
```
