### ISSUE TITLE
Endpoint Password Field Should Be Shielded for Security

### ISSUE THREAD

**Issue by jodom961** [jupyter-incubator/sparkmagic#714]
# overview
Ideally, when a user enters a password it should be shielded like a traditional password field. 

## current state: 
![image](https://user-images.githubusercontent.com/13648529/120516269-c86b8d80-c394-11eb-9fcf-873ef51ec2bb.png)

## future state:
 
![image](https://user-images.githubusercontent.com/13648529/120516322-d7ead680-c394-11eb-8288-e44d42106f2b.png)

## implementation 
https://github.com/jupyter-incubator/sparkmagic/blob/f5d4a7ad39b7bc47fb23cbe0269ad669289ba1f5/sparkmagic/sparkmagic/auth/basic.py#L50 
should be updated to use the password 

```
ipywidgets.Password()
```

should be a straightforward fix. 

## widget factory 
https://github.com/jupyter-incubator/sparkmagic/blob/f5d4a7ad39b7bc47fb23cbe0269ad669289ba1f5/hdijupyterutils/hdijupyterutils/ipywidgetfactory.py#L43

**Comment by devstein** [comment]
Will be fixed in the next release: https://github.com/jupyter-incubator/sparkmagic/pull/698
