### ISSUE TITLE
horizontal scrolling of Pandas dataframes

### ISSUE THREAD

**Issue by philmassie** [jupyter-incubator/sparkmagic#721]
**Is your feature request related to a problem? Please describe.**
I very often need to look at dataframes that are wider than my monitor. Spark dataframes wrap row by row, but Pandas render out pretty well, providing a nice scrollbar. As a result, until now on a normal edge node, I would do something like this:
```
pdf = sdf.limit(5).toPandas()
pdf
```
When I run this in %%spark, the pdf wraps. 
In local, for some reason pdf renders as 'normal' with horizontal scrollbars.

**Describe the solution you'd like**
I would like to be able to quickly inspect table contents, wider than my monitor without the awkward step of transferring it to local first. This is possibly already solved but I can't find anything.

**Describe alternatives you've considered**
The only way I can find is to collect the spark dataframe locally in pandas with a dedicated %%spark magic.
Perhaps there is a way to make the notebooks width much wider, this might not be a SparkMagic thing at all.

**Additional context**
I hope these illustrate what I'm on about. 
![1](https://user-images.githubusercontent.com/18571935/126361425-32df89af-70c8-44ea-967f-b82e742c9739.PNG)
![2](https://user-images.githubusercontent.com/18571935/126361446-8983550d-a8a2-4bd6-a7a6-7c7c1d1c8c8b.PNG)
![3](https://user-images.githubusercontent.com/18571935/126361459-58d2df9d-73da-4b72-8207-fda598e00963.PNG)

Thank you very much in advance

**Comment by devstein** [comment]
Hi @philmassie thanks for making a detailed issue! This is a common issue with Spark and is not exclusive to Sparkmagic. There are two existing solutions I know of 

1) Use the `vertical=True` flag for [show](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.DataFrame.show.html). This makes it much easier to inspect a few rows of a wide table.

```python
spark.createDataFrame(pdf).show(vertical=True)
```

2) Use the new Sparkmagic [`%%pretty`](https://github.com/jupyter-incubator/sparkmagic/pull/688) magic; however, you need to be in a Spark or PySpark kernel for it to work

**Comment by JianweiChen** [comment]
%matplotlib inline
from IPython.core.display import HTML
display(HTML("<style>pre { white-space: pre !important; }</style>"))
then you can scroll horizontal, even in %%spark
