### ISSUE TITLE
Missing comma on sparkmagic/hdijupyterutils/setup.py 

### ISSUE THREAD

**Issue by Pokiharena** [jupyter-incubator/sparkmagic#733]
Hi,
I hope I'm not flooding  or x-posting 
Following this [documentation](https://docs.python.org/3/distutils/setupscript.html#relationships-between-distributions-and-packages) shouldn't the following line contains a comma.
https://github.com/jupyter-incubator/sparkmagic/blob/fdbd44fad258c8bd6e889d274fa14ed1b7726188/hdijupyterutils/setup.py#L64
Is this expected or a known issue?

**Comment by devstein** [comment]
Hi @Pokiharena thanks for making an issue! This is not expected nor a known issue. Would you be open to making a PR to fix it?

**Comment by Pokiharena** [comment]
Hi created a draft [request](https://github.com/jupyter-incubator/sparkmagic/pull/734) requested but I'm not sure with the next step. Could take a look?

**Comment by devstein** [comment]
@Pokiharena Thank you! I left a comment, but once you address mark the PR as "Ready for Review" and I will approve and merge
