### ISSUE TITLE
Run spark magic in EMR on EKS

### ISSUE THREAD

**Issue by luissantanacontato** [jupyter-incubator/sparkmagic#735]
Hello everyone, 

I am using EMR on EKS service in AWS cloud and the only tool for write code is aws cli or EMR Studio. The Spark magic could to be the tool for this, connecting with virtual cluster. Are there some way for this happened? 
Several companies are using EMR on EKS because low cost. Make sense?

Thank you!

**Comment by devstein** [comment]
Hi @luissantanacontato Sparkmagic is an Apache Livy client, so to leverage Sparkmagic on AWS EMR all you need to do is run a Livy server and configure Sparkmagic to connect to it. Hope this helps!
