### ISSUE TITLE
Sparkmagic kernels - Doesn't show widgets

### ISSUE THREAD

**Issue by Armadik** [jupyter-incubator/sparkmagic#779]
**Describe the bug**

**To Reproduce**
Good day.
I can’t figure out ipywidgets.
It doesn’t work on pyspark kernels (using sparkmagic==0.20.0).

**Expected behavior**
Similar work of extensions for the pyspark core

**Screenshots**
![image](https://user-images.githubusercontent.com/50964282/197758587-e2a57511-86f0-4ca3-9c85-5d9608109084.png)
![image](https://user-images.githubusercontent.com/50964282/197759172-ed5bdcb5-ae53-4609-9c34-36df2be6bf5e.png)

**Versions:**
 - sparkmagic==0.20.0
 - Livy 0.8.0
 - Spark 3.2.0

**Additional context**
autovizwidget             0.20.0             pyh6c4a22f_0    conda-forge
ipywidgets                7.7.1                    pypi_0    pypi
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
jupyterlab                3.4.4              pyhd8ed1ab_0    conda-forge

**Comment by rabejens** [comment]
I figured out a way using Pandas and Spark DataFrames.

You first have to make a Spark DF on the Spark side:

```python
import pandas as pd

pdf = pd.DataFrame([["apple", 40], ["blueberry", 100], ["cherry", 30], ["orange", 55]], columns=["fruit", "supply"])
df = spark.createDataFrame(pdf)
```

Then, you must bring it to the local side:

```python
spark -o df
```

This converts the Spark DF to a Pandas DF and brings it into the local side. You can then plot it:

```python
%%local
df.plot.bar(x="fruit", y="supply")
```

Or, to use `ipympl` to get zoomable and scrollable plots:

```python
%matplotlib ipympl
df.plot.bar(x="fruit", y="supply")
```

See:
![image](https://user-images.githubusercontent.com/8402886/199979198-7983c2cf-19fc-4c1f-a852-a1d9f256ca04.png)

![image](https://user-images.githubusercontent.com/8402886/199979255-4efd025d-d4bc-4997-83cf-92fdb71b54ca.png)

A word of caution though: You should preprocess your Spark DFs on the Spark side to not have too much data in them so they don't clog your notebook.

**Comment by Armadik** [comment]
This is what you need!
