### ISSUE TITLE
Manage livy endpoint from magics

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#78]
This will be the API:

* `%spark add session_name language conn_string`
  will create a session against the endpoint specified
* `%spark info`
  will display the info for the sessions created in that notebook
* `%spark config <configuration_overrides>`
  will add session configs for subsequent sessions
* `%spark info conn_string`
  will list the sessions for a given livy endpoint by providing `session_id, language, state`
* `%spark delete session_name`
  will delete a session by its name from the notebook that created it
* `%spark delete conn_string session_id`
  will delete a session for a given endpoint by its id
* `%spark cleanup`
  will delete all sessions created by the notebook
* `%spark cleanup conn_string`
  will delete all session for the given livy endpoint

This covers #56, #75, and #76 for magics in Python kernel.
We are not designing the API for the wrapper kernels here and we'll tackle that as a separate improvement.

ping @msftristew @ellisonbg to take a look when they can

**Comment by msftristew** [comment]
What information will be included when you do `%spark info`?  

Anyway, API looks good.

**Comment by aggFTW** [comment]
It will print the sessions you've created, listing `endpoint, session_id, language, state`

**Comment by aggFTW** [comment]
Due to the way that argument parsing is done for magics, the only way to allow for configuration overrides for session creation in the `add` case is to add another API:

* `%spark config configuration_overrides`

This will save the configuration overrides and every session added after it will start with that configuration.

Thus, add will become:

* `%spark add session_name language conn_string`
