### ISSUE TITLE
Reference Livy alternative in Sparkmagic Readme file

### ISSUE THREAD

**Issue by pdambrauskas** [jupyter-incubator/sparkmagic#782]
Hi, since it looks like Apache Livy is not maintained anymore: new features are not accepted, Spark version is not being updated, we decided to implement our own solution - [Lighter](https://github.com/exacaster/lighter). 
Lighter supports Spark batch applications on Yarn and Kubernetes, and PySpark Sparkmagic sessions.

Some more information on how it works can be find [here](https://dev.to/exacaster/spark-is-lit-once-again-41p7). As well as on documentation pages in our [Github repo](https://github.com/exacaster/lighter).

Would it be ok to add a link to our project on the Sparkmagic readme file, so that other sparkmagic users would know that there is an alternative to Livy, which allows to use Sparkmagic with latest PySpark version on K8s (and also Yarn)?

**Comment by devstein** [comment]
Hi @pdambrauskas thanks for making an issue! Absolutely. Alternatives to Apache Livy are much needed, so I'm excited to see how [Lighter](https://github.com/exacaster/lighter) evolves.

Just make a PR to add it to the README. In general, always feel to contribute to Sparkmagic. We are always looking for more contributors and maintainers, especially people that work on related projects in the industry.
