### ISSUE TITLE
Expose session configs through wrapper kernel

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#85]

**Comment by aggFTW** [comment]
Session configs for magic kernels will surfaced in the following way:
* If no session has been started, user will have to run `%config {}`
* If a session has already been started, user will have to run `%config -f {}`, which will delete the session and create a new one with the applied configs. If user doesn't provide the `-f` argument, an error will be displayed and nothing will be applied.

Question: do we want to preserve the properties provided by user across notebook restarts/different notebooks? Right now, we could preserve for both case or for neither.

**Comment by aggFTW** [comment]
@msftristew

**Comment by msftristew** [comment]
How would preserving this state across notebook restarts work?  I don't know what our current approach is.

**Comment by aggFTW** [comment]
We'd have to modify their config file at runtime... :S

**Comment by msftristew** [comment]
I vote no, and honestly that seems like it would be very unexpected behavior anyway.  Preserving those configs across different notebooks is exactly what the config file is for.

**Comment by aggFTW** [comment]
Me too. This means that for every notebook, user would have to keep cell and run to override. I like that behavior, but worth posting the question :)
