### ISSUE TITLE
Expose livy endpoint management through wrapper kernel

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#88]

**Comment by aggFTW** [comment]
* `%info` will list the sessions for the livy endpoint that notebook is running against.
* `%delete -f session_id` will delete a session for the livy endpoint that notebook is running against by its id. Without the -f, an error will be displayed telling user that running Spark context might be affected.
* `%cleanup -f` will delete all sessions for the livy endpoint that notebook is running against. Without the -f, an error will be displayed telling user that running Spark context might be affected.

@msftristew

**Comment by msftristew** [comment]
So the `-f` argument is always required for the `%delete` call?  That seems wrong.

**Comment by aggFTW** [comment]
Always required for delete and cleanup, since they are destructive operations and we want users to understand that.

**Comment by msftristew** [comment]
I don't think I agree with that design decision.  `%delete` and `%cleanup` are obviously destructive operations by their names.

**Comment by aggFTW** [comment]
From the running notebook, you could issue a cleanup which would delete all sessions, including the one created for the running kernel wrapper. That's the rationale behind the `-f`.
