### ISSUE TITLE
Support notebook >= 7 

### ISSUE THREAD

**Issue by sergiimk** [jupyter-incubator/sparkmagic#885]
#825 highlighted a problem where `notebook >= 7.0.0` causes `sparkmagic` installation to fail due to removed `jupyter-nbextension` command.

A [workaround](https://github.com/jupyter-incubator/sparkmagic/blob/6eab8aadfa3c61a6247868836b2a8df086e1b649/Dockerfile.jupyter#L33-L36) has been added to the Docker image that downgrades `notebook` version to `6.x.x`.

This ticket to provide a long-term solution and remove the workaround.

**Comment by devstein** [comment]
Should be fixed by https://github.com/jupyter-incubator/sparkmagic/pull/935

**Comment by sergiimk** [comment]
Can confirm the fix, closing
