### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by tleonhardt** [jupyter-incubator/sparkmagic#934]
The last release of `sparkmagic` is [0.21.0](https://github.com/jupyter-incubator/sparkmagic/releases/tag/0.21.0) made over a year ago on 2023-09-13.

Would it be possible for one of the maintainers to put out a new release? Support for Pandas 2.x was added about 3 weeks ago and that is a key feature for me and my team.

I think the new release should mostly be good to go - I think the [CHANGELOG.md](https://github.com/jupyter-incubator/sparkmagic/blob/master/CHANGELOG.md) would need to be updated to replace `Next Release` with a version such as `0.22.0`.

@apetresc @jdfreder

**Comment by tleonhardt** [comment]
@devstein I see a lot of contributions to this package have come from you.  Is publishing a new release something you have the power to do?

**Comment by devstein** [comment]
Hey @tleonhardt yes I'll get this done today

**Comment by devstein** [comment]
[0.22.0](https://github.com/jupyter-incubator/sparkmagic/releases/tag/0.22.0) 🚀

**Comment by tleonhardt** [comment]
@devstein Thanks for getting a new release out so quickly.

I see that you ran the [Release workflow](https://github.com/jupyter-incubator/sparkmagic/actions/runs/11811065707) as instructed in the [RELEASING.md](https://github.com/jupyter-incubator/sparkmagic/blob/master/RELEASING.md) guide. 

However, I do not see the new version on PyPI: https://pypi.org/project/sparkmagic/

**Comment by devstein** [comment]
Thanks for flagging @tleonhardt, looks like the new release workflow doesn't trigger the publishing action. I re-created the release and it should be published to PyPI soon.
