### ISSUE TITLE
Allow user to return dataframes not constructed through SQL queries

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#97]
A thought I just had: Currently we only return responses as dataframes if their query is a SQL query.  Since we already have the code for parsing dataframes from JSON responses, we might provide an option that lets users say "I'm going to output a bunch of JSON here, please parse it and return it as a dataframe", even if their code isn't a SQL query.  This could be useful and could allow users to get arbitrary semi-structured data back from the remote cluster.  I'm not sure how feasible this is, or if this would be too error-prone, but I think it makes sense and could be really useful in some niche scenarios.

**Comment by aggFTW** [comment]
Closing this until we get a better understanding of how it would look like. We'll reopen it again then.
