### ISSUE TITLE
use_auto_viz is false by default?

### ISSUE THREAD

**Issue by msftristew** [jupyter-incubator/sparkmagic#99]
Is there a reason for this?

**Comment by aggFTW** [comment]
Not ready for prime time.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Wed, Jan 6, 2016 at 6:09 PM -0800, "msftristew" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a reason for this?

-
